application: peppy-linker-102423
version: 1
runtime: python27
api_version: 1
threadsafe: yes

inbound_services:
- warmup

handlers:
- url: .*
  script: main.app
- url: /
  script: task.app

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
- name: MySQLdb
  version: "latest"
  
