import httplib2
import os
import sys
import itertools
import logging
import logging.config
import time

from apiclient.discovery import build_from_document
from oauth2client.client import flow_from_clientsecrets
from oauth2client.file import Storage
from oauth2client.tools import argparser, run_flow

from apiclient.http import BatchHttpRequest
from apiclient.errors import HttpError

# @Author Daniel George
# Sheepdog
# @Version 0.9.1


# This is Alex Moothart's channelId, for testing purposes
uniques = ['UCXqK1FO9yS8x7CMGkzLgJmA']

# These are unique commenters for Alex Moothart's channel, "The Moot Point" for testing purposes
# channels_list = ["UCdLWVR1C-hwcW4i558GeZ1A","UChuJTHTRhqBTsP3KCKyIieQ","UCTWdDAN_QrxWSumDs0z2bpA","UCQYfPb1c6_vDLAbGxSRUT5A","UC63nu_KBEVeVOlvfo-1D_Kw","UCiNUzLpahS0TjBgjobWdjNg","UCJY4haGpJ3Foymmdjp8S_Tg","UCOH3EONTobdSpSLz_S7W3lQ","UCHqg-aWTWbWHPpUliI2B-Vw","UCB6cbWd75lPW27rntPlLKow","UCcc_zG4pMLpuefQQs25e4bg","UC7Q6GvTqbiCIgqcNsdz-UEw","UCTCiI254D8lP1jNWYoc_RrA","UCM47dPWICE2zhPiMpa2Y-Gg","UCZ9E-vZyFw5YXL75u5PvrxA","UC6hwEfhOV8_kj61n7lk4wNg","UCoXu15iHZqmqIDGVsJlKucg","UC184MUWk-JadrboW8F9wFlQ","UCp1wRB2SHD-5PzL3Kt7crSg","UCUEt0vbfmLBvQEPDIFzAvkA","UCMR2NymnsFVloJxGQ7ILwdg","UC1ahXRNBL9vxmun4W2l8_uw","UCmZBrgkunOCGchMX9fnN96A","UCrlt-HmI8zeJaMhvqQ-MLSg","UC8yhMy7fVE86IfYRvo_PecQ","UC1snbc_vpLJgbDhOXxjbbPA","UCSeMnbw4jSnYNfzcvzvoVYw","UC7mi8f4ikb35Hz81nmNZmWw","UCfYkvwAOpt1zuCn2HkST93w","UCLYOZQ-Q9WDnCac0h7f46fw","UCD_ioRy-ICjX96iA_XZzM8g","UCFL6hdpOCq4bJ8cUsKga89w","UCUbUhCQXRrIoaVAFWvMOXUw","UCPD5r_CobvhHNTDLWVRhysg","UCuU8RHa4InGLMzoKtPBgVKw","UCKyO47S3Qqh7P6azvTPFpog","UCtK_ECnDfnd0z6wSOllMfFg","UCWkuh8bPrMthW49TFo5s1Mg","UCVKXsLBEleteY3Xl5yNIucg","UCvPM5oi1iwxb8DOziDkB-5w","UCGgvlOsxkN0ZqyYKqzTVzdQ","UCiuvBLPXSSefN15duJV36kA","UCxgZjzG87I3fXDcJCsJqlVQ","UChEgEbYmWFkVd46H_sBgajw","UC365Wb-Gk5Dxs0fqSzAmFLg","UCpqhnm8UqttRswwmI5ZWYew","UCWWRX7ZVmDbBhK1g13aDhlw","UCUWRrRcm1gYOpk_jK_svp-w","UCmu4-oVRRFDYk05DpyczotQ","UC9ZOJ3SGXFyOor6-4B1uRrA","UCocFdT9iSKx7osu0rnoNmGQ","UCtK_ECnDfnd0z6wSOllMfFg","UCsvJSMpnq9BP0HcstUASK6g","UC8nuvKdNBtY90ELrGvLSgSA","UCuKZh8xnED8Q6y3mf6Ie09A","UCwKMocTcYbYBm8tBV4kZ--w","UCFUr8bIlkMT1y9-OpT8Xn5g","UCVN_-AmwViHcPbDFhFhMv9Q","UCUMlFGNp4V6oiFCe_1WWaYA","UCkdFlxQe836q841RrDxueiA","UCewaP3rEFibp10FRGgufjZg","UCj-SrH1hCXqlGVC6GfXXvaQ","UCuh4cci7H6Ma66GMJ8s5Q5Q","UCnr1Rx6WF8UAeK00NhERrqA","UCi3qquNhMZWQtgSJiTN5AqA","UCTxTSEL69rrBzk9NAOZDl-g","UCFEZy2WPzGvqvIyr3nL6xBw","UCB7drWRe7B8Z6afod6agRWw","UCN8hZ0Q2bF9tlQ8Lqrfy-zw","UCgf3c6riglg3m9Oqofa7VDQ","UCzxoX7I_AOeMn-yzibquoMA","UCBCyDxn-iQBkx8Keq8aufHg","UCZDvO_3q_xlCzUEzp3DCzlg"]

# list of uploads by user David Levitz,for testing purposes
# video_list_uploads = ['SvCPECRlF0Y','aFYKjHATc4U','JTF1RfW6TdA','2L6mwNfd9pg','GMGNObMXyh4','sgauaEFs-yI','ZazedtACt2U','r7RWtVcJqXk','H7poks-lCS0','LVLYEfRwPbc','-72dGvS1uXo','ilDNdmlcU5Y','A3X_hpA5-ts','WNIzPXyNTZ4','A6mWPws0n1M','TQvRUcHt1xM','DPrf1pUP7z4','5H2cSV12Qhk','nRRGva6q1UY','YRnf-TaEa_U','sJn4uc5korA','bJ8cb2MQqrg','BvREoDV3J60','FmtgUFLEC7U','WsK6vtlwtdY','_C93BHzKK1k','xdSpQDvKXCI','tTzGe_MkMTw','VGqAX4-oZK0','nAxgkoIqARA','VcyNxckw0iE','RO0HRDvbOHY','Om1Mj27-_6U','1ysu33GZGHI','S3SdptKmhG8','eyVT66_CxnA','4dI_6_Kvfe4','IinCg2kreVw','Os64DMzHqQg','j7Bg8wiVSC8','KDrr-6UtTBU','hYSD_UkfZ24','f-Tv1XdGKrM','RFw8iNPu4Xw','EjJwe8bipbE','ilOEd4_6odc','mC7CfMpRur4','OyL2Kt2mu_E','iPngUGZcbT4','PCVkMVHsb2A','LW_wRyBPH74','73_e4z4my1Y','jAuu1cJA6X0','0I6dqjnXp2U','3MIr8F1C2P4','52e_vp94TMo','yyCNiQ_GC1k','kw7UtLmsOyo','YiXf8v6RpC4','V5HdDlDO32M','bUA2n72TYmM','v0QUO27FzDs','PN-OJ5Yl4tA','X-gc60MSqIU','3sKzMDDQLNQ','UGMNiyE18hA','IEgwhLZSZ30','awpA1BWPb3w','RXjyLLcjSFw','zpZawGa_a1Q','5OACYz6d6_4','4mrul878ksc','LJxkVT98af8','KGHDeNzx1bA','w192pqB4utk','q3TGNfuUHOw','fISm8UYUphs','AgLhxA-GPKA','MY5o4n1Cdk8','H3-5-wKUUVs','GCiofe4Bcbk','FJPbL6k2elU','RhHmUaH_rDA','5KNo-ICZGmQ','mNMeQA9hslk','uRu8FcrbMeI','jbx18ZleRnY','yFd2jJQ-9b4','w0o8gv8BRIk','QMSz7ygw6Hg','v1mrrabPy-Q','oxwVCsM_6j8','TOvuIm4XFdw','dtVD-aG93xY','H5-tPiUFC80','dM-G-_lquLw','vkOX_t5nWFU','VbwJib0g1is','RinpNsztDRM','-F64shQ9F80','b-2A5RA1X00','D5_Y5rK-Mms','LhzKt4JIrnw','w1tMl-ohZxo','6wVdHYGu2uM','BlWVZ5RA-48','XJN_hCqzKKE','MUybQ_sRrUA','lIRmmeSku-M','s8wD1N9dIEE','aWdJGycMzuw','6m4-xnQ0Yk4','iVy7D7423is','6NQyA3sw4G8','CbwOBLTstOc','KSzyT3zkgAQ','kxMyJZZMJ64','29lrP9-YzKI','TqPsxko0JSs','ajnk80GGB8Q','_EsEgKUkASE','Ic4Md5EdBAE','FBoTsX2qios','ItAoMCd-bbU','q9VAqLqow-M','G316xl-qDiM','o7yfxX4vS4A','Eybt-mT4ij8','DD0by6jR97s','3ULuyN9Nag0','q3rMOlDtVh8','Xa-G29_Ee0w','CSXMUzmghnU','n7ImvOpWx1k','n0c3XUmUZHg','ojntvwyxWuc','tfM6XZ3adMs','WO9cUFiR0Yg','0qZB6R9mFiU','fzqMrd6a-qk','GTn63lGCsRs','0Z9knVwhfyk','QvMHNaobJmk','u5_4Xos3twY','uGIYqv3zEJY','vYaMLriaaPk','oXhKGRem-UE','tK-FXlJuIpQ','UzrBxK3h20Y','CgepMP-X5-o','fVOWO727SFU','VMX9jH9eouI','u41fe-V9zus','0DfisfebQHY','ysW3FKVLhu0','r60AaMqKyEU','firDLHqofNc','TCct4s7sU48','JcdEdcn5R68','86e3OpN6a3A','F8VTDg_hzRQ','MmmJCPsD2xE','HaZ_VKo6zN0','aG911UCSChc','RZnSKx27tb4','InfM2FTVqn0','lIO3nZJaFGs','EcjcTFt0aBM','_7O42iSdc0w','2fRiY6I09WQ','1fAmnZ_rz9Q','bAo0HTgmBTE','Y2w0LGLjKWI','GjmdqyAjFFI','sHjLLmn6s7c','b8E7EBOk3Bw','1lT6mtSCxtM','daESLs1mLjM','W64g-pQxskw','HhK9E3uEa8Y','XaFU6PRU_dI','wYuzf-wvhyM','zn5NzNdlki4','oibalZjFh9E','uLPRImYZ0Fs','5vyTCPosD3w','XEaE2JRqEGY','FJw85ghHyI8','4eHgWuZHSWw','LAPHAfE-k0E','FDfYpiyTQSI','rAGOX79Hg_E','GDIx42iEjZM','vXbp0qZjy0M','ECBeaQy7Rmk','RLzrzI0EuaI','kKxcpD6LLYc','7GZL92aWf1M','_8be0Yw9ZsI','BXbmIqnghA4','yPrD_Io8S8c','bUKwgTwesiE','8LJu4bc3lD0','nnOqZEbGL9o','mwvBSoEoP_Y','m3Y8_yPbLIw','B8m95hRJKJQ','W27SO87pyvE','G6PbBRs0Qvg','O4IYHh5304s','mk3O1DqqyKY','P7SAsgBB4LA','mVAJPNEAnxo','CzzU6WbFZdQ','ezjKZkzEBWs','SbwF6X_JqMI','17fTOvfLe-M','F6FCgujn0qY','51dz4NRHYkg','s8zz20va-qY','NrB0V9oWSvc','pjnFok3sOmY','l8_oZvsAecg','_vGigxK2jq0','6SkOAUzNJlI','1Ss4W0XU4_U','M7dak06SEQw','qxigLXvXn80','T4ZaXyYeBkY','sSI9RhHJuyw','Q5pSYvjTgdE','Q7D74XOF_8U','ZJxE47C7nHA','AQlbSmQEblg','aBAyUkQP2Ws','gN-P1hep_qk','gwdbLe6xGa8','zM6kiGmZNCw','T2CGAKS5h3U','sMa2r-hlRLc','hsp5bmnKjGQ','5l6_ZHnt-W0','UYBghexu9ew','m1SaVNqyStg','LuR1zuC7yuQ','YSBKl-DHnBs','zWqC1oKFFsw','VX2HvdqL_-g','CILKHKi28TU','J7YukGw1KxA','NhUkZvjvY2Y','kVXVHT0Lh2o','uv1flJO3Q9w','lL4e5Tn0ZWo','RWB8TEfD_wI','ZPNVn6XnNDw','SUe5MsXVqdM','tThc2KVI99k','k8nw5iYob9M','EmFWrYMe5Ys','kGYBwG_cwbQ','9Et4g1M-Ivc','uoY5h2nNW2o','X2XlhVVQqNU','hTLFSRDLcN4','EudlROef4-I','GmZr-FiXZ1w','8FdqoRATUGk','UuibkXv3ucA','U-SHBPSDRQ0','BKEBwU1oS6s','3a3vE7dldu0','UOPiLl52olo','Y6JGAQpHWQk','6A2RagnrHHI','CcPx3sTnDmg','xczhyM4eDNg','b0KHMEykcIw','Q394V8YnWYE','J03g7Q_O7wE','wS6RgygN_9I','uNUScF0Izo0','_uxKJRdxxMs','Ljd34jrxYOA','SRX-zLeltyI','E0qa4fMV4f8','X1Lwz2iRaD0','g3vSrrf3lXA','HkzvbChKOLE','O4BDZ0A8FL0','aksCkku66QI','AGWdQHgG4Gc','iMmTtXpmcAo','OoX0VYQwSdc','Eg72RfELJ9Y','l9NAcAsqPdA','-iwLPmLT4Fo','_WpGkKyz8aU','7gvASGDdj78','GoDgmvetHEM','05aa0Qjdk1E','t-zwf201dyU','s9O0OAUZjqE','IajWB7D5Aw0','HORjDwnopkE','RhdzEX15IEM','91wTt5EHnPQ']

# not totally sure what these channelIds are, though they are probably unique commenters for a channel
# uniques = ["UC-09qnwbeSTXXS4V_1bMkqQ","UC-32yDHJw-nfolZJ9uTX2SQ","UC-4V3usFsHi0zfJcsKNU3Yg","UC-9F_1W0lIo7_Ls-F8vcyQQ","UC-Lt5MBDG-QcePEa33gxMLA","UC-O02q7WTEXPAQDXkPpeSGw","UC-PYsbhYR8rpa2TwuDWdPtQ","UC-Sl5PLB5h42ghcK9o5pfBA","UC-YBBJwQU08urxeeCsleSzw","UC-ZOf1hVtsepaqG0tzOsfcw","UC-_W4-zn5v9ftpgoG7kJdig","UC-ddpCEhp73jtIGPeOmoFjg","UC-hGubLV55DT2ZlFH33dZKw","UC-hcXmqwSLb50C6sqbQcTMA","UC-iOAaoBTBzEXnlThx368lw","UC-jQdI-FJSQx41PmJqMTWNQ","UC-jtAGfNLvj1waNPNfqmfDA","UC-ppTKISofaiNm_C_es2hGg","UC-qk-ogA4JiOheDq385Sq9Q","UC-sUAJw6NcWnd249tqkLncQ","UC-uU12UwDMqdK4-rckzzqGA","UC-wUWxmfHPrTuzzJPSMLH6Q","UC0-dnwq71VUc76lSUvAH20w","UC0-sXj4Ny53SyENyIiWa1XA","UC03DbKEGFAa9byoDWgTBRlw","UC03tLnTbyVWqGb-mlB9tBMg","UC084-BO8vA98-PsYKcx635w","UC085qROe9IfGI23ImrI8Wpw","UC0D_fVxagffFQDIv12btWPg","UC0FST45FL6lr-6N2_PaLuoQ","UC0FXOGEdXpYl1akM5NL9Jeg","UC0GWyX13rEVRLziCxSaRmJg","UC0KY9MtxnVQD7YG7DekEYgg","UC0OE8d6gds4hNC6h396NcJg","UC0Rm6ohxWXi3QE5BJoaCZ2Q","UC0SYkIS2sLjDg8E3yfNtZiA","UC0amdMRA93CdmaPIqG3Gqpg","UC0cm24TmFeuHB4na355uGdA","UC0gQoqAATn6TcJ03t6KK6NQ","UC0hN96q2yNIuSXOhnkidE0w","UC0p9z-Vz6rFhKCXTkYt9iVw","UC0qaFuBhafzhCje8R4u3DSg","UC0tcbhXWLq2nmaYUdvj3MCg","UC0u_3PfCBMry2GrSdXinjPQ","UC0ucCDKlkqza-KirETqwASw","UC0vgMneiik0LWXi6J04OsLQ","UC0xA4rdsF4ZUcmwCtIiMs8A","UC0yoApUx3MnliKD2PxllP0w","UC1-CiXuy8X9Ib3cZsm1zGSw","UC15kS6ncWqJ3BQO7CkgTaPw","UC18G9y6NrnvgVuRJIAGVc7A","UC19fV8RvVq_yKAvsYJWnlNQ","UC1E27KF-DifLVKMKmu6lCSA","UC1E505II-15ctOYCKkdBnKg","UC1FWo5UkmJgTltzyoaRFfUg","UC1FgbhkNgO2jknT5cB02kTQ","UC1G21nZaFQUpleqzoXga5_A","UC1MS1BYemqWgavEH87lSp6g","UC1OcaVefHkpjiu3I9q63b8Q","UC1R25p2WAH3Of09Bmwd03iA","UC1SpID8TLyuFZni65B--J8w","UC1V9XENXA31W3AT3GKXaOyw","UC1X1yQFv-bKAYgGl-Y-M0rw","UC1ZDNVtrXlsXFzh8VuY37gw","UC1hE2ugm9qSkBNP5RRhOGTA","UC1in2uei-FQWTKzakUEC5Qw","UC1nz5SoN8ug8ym_7VfUaoOg","UC1qNvtho6gMnCkD7Jh4pLgA","UC1wo0mkREC26W2GOkREkGkQ","UC22k982HqKjl7tz2k6CTbaA","UC23H-IzKVY3F8QtFoTAG_jA","UC25PyoSkE07MXneyROTxARA","UC26zYz5jcogU23I20Igj-pw","UC296iJaMY88WC-3MA8KwSpQ","UC29pyLmMSPu0Dynw6K5P1Xw","UC2DvShyEzlBGSLnShjS7MMQ","UC2E1D81B9ikJ17kY4VVekRA","UC2EPCfJjjzkJvdFFwALQBcw","UC2G7MqiHcBerJQGDbiMaOCQ","UC2GS3PTVhKIAahMXbCsq_0Q","UC2GY4bK9QPhrNKuC21f5kWQ","UC2GsptKRCm29m-lgFpQpNmQ","UC2OEat-GFptLw1v26UUTPVw","UC2PA-AKmVpU6NKCGtZq_rKQ","UC2SvIXIzwl4JXXVaNf_0uvA","UC2VdflOK359omP7Tc-X3zvg","UC2XH-9ScQCphR43qJMeoF5w","UC2XNRIWO0au2P1vHFnEdoCQ","UC2XeWQbkTbX-0iWpK4j-QRw","UC2bhpx_QXKTB23fPijvbLPg","UC2dh0Ufpszk9ZLp_xiSsqvg","UC2hFdGMm3FHZ8qokBGx7tAg","UC2iMqequs1IO5uZvf1rXCnA","UC2mXSjiwaEXljk64-YXb5eA","UC2priGizIsSvABYq-zsw0NQ","UC2qXHOafHAC54N1k6RgEgwA","UC2sWFUUif_embtRo_vuvkNA","UC2sn54iP737gReh80Hb4qcw","UC2svYp4IOUlPg0GDac9tjpA","UC2tZtoYOW3gZe2fHfTYtxgw","UC2tniEV_TDnU6nqrVwPcfnA","UC2yRfmJ30mg13O3rc3GVE3g","UC30JvTr84T-d8b4t0DQr5iQ","UC33nxLR_vwecz54CdcuSSJA","UC34WV2ehhTvLW0xL0TllJnA","UC34gI_lKA46mrbTXBJCv9Tg","UC35BDyDGGe21f79xm9J5wAQ","UC36PKP8nN-R6NSbLH_alPFg","UC37YQ6Nm-XCXpEYLdczAcDA","UC3DRrM6yAsqmtH9KponCt4Q","UC3HvwOPH-xwVb1aWoVg7ohg","UC3LYhyV6fyoX9T0sp21iTPA","UC3UnjMBVe25T6v0xFcUD8Iw","UC3WeNXGkrd8NaWa_UhXfpiQ","UC3aWeprvD0eWTzLeAHBjRcg","UC3d_rquCGoHfq1kYp21_2_Q","UC3evq4KMQxIHQ3z073tiOrg","UC3ljXUD2j0TFL-vwhu6NdNQ","UC3miARNnwsg4lfVNLjz5Oug","UC3oE-RRFb_jN4Y0aNlMSwGg","UC3p5-scKNrAI4qKSXYNHAgw","UC3pX0U1mQnsauKAH6x1wFSQ","UC3xJM2neG0YdrTyxb2k8yBQ","UC3zS1zPISkH2d8oa_d4TWtg","UC4-Bws40YV20liJYW9H5w9A","UC4-anBJ5G_cY_IdIXt1ZA6g","UC40RPb9tvOgA6f44n9WaorA","UC46378fAhN8o2FvucmN1HUA","UC487OOdiAhHIRU4BVChBTRw","UC4BMKHgd9wfpP-FXCEyGWcw","UC4CVuQ5fXqE4hphAR_15TWQ","UC4DF_cXJqaCk5St-iiFAOxg","UC4FoQyAARJaFU74MTn6FRDQ","UC4GizRDRPzXJJ3s5BTvcVNw","UC4H6oFlui0iFD4v-mAF0czw","UC4HVjuv-rrT3OH4Nr1jvBZw","UC4JWsThihBLL2p3oBjha9Bw","UC4MCttz-rgKNenTt_0MlrOg","UC4MLTl9vYRSPLOLiajg9r2g","UC4OF6u4_yL5zZDG3Z88r-xw","UC4PcwV6AU8um14mh_AbRscg","UC4WOE2kwu2o2Ml_pKbt0sQA","UC4XwPjKVoreSyZgxHzvPHdA","UC4cpPLGYEE-547J-BBvLGqg","UC4fdCk3zZiXfvSoYyGx_YoQ","UC4gd-VoB7Mei7deVN9lORdw","UC4hJkcsr_miLDb-uFqA4upQ","UC4icuHhHgcZ9WJ7_lPrtaNA","UC4ln2pM3qpm6g2s9jaXgBgQ","UC4nhnpa6w3quYPn14kg4kYA","UC4sE_4NMAghZbsVkP7b-IsQ","UC4wwadO4lMgEh4onpepVdaQ","UC4xgLlktBk8aCGrzFU3L14g","UC4zu0jWDq9-pfqgAznv8ZuQ","UC55ybxlvSKaVhtjMdXLWggg","UC57KYrZQbnfm4qYnFdZ_gug","UC5D1jzJSBtOKsCsGNA19EDw","UC5EkGY1yGC0T-2abCpPZvjw","UC5OXiz9mQXTKPDc7IHkiyGQ","UC5QMczA1d9QIZcxPSMLltKg","UC5R24w6c00nI8xbg_--FMcQ","UC5WHGZdx5azzQ7oB0suRsLw","UC5Y4PF7HhOht-X2GAn-oGeA","UC5ZfbO5IZdVXd60jKPospsg","UC5_0wwIzWb79ymHZT9R-3Rw","UC5bcu77HjII1EI296rhPI8w","UC5e_nDGeMQIT51lunwtcICA","UC5iVPeQH2BGvmdM0Y4mIEcg","UC5k7yU_7rgtpdeWkqRcGWrw","UC5lvwDO6TQ3JwmwR5RbCSPg","UC5n5QZ55M_XDc0IHGtvhWGg","UC5qKFX7lZfN6cpCFPZGzQKg","UC5sUDe1fjjiu9zSg-TxHluw","UC5vBc5UqhMZkiYyyZ4shZOQ","UC5wMZvUj_WrvhHjILg4k8Rw","UC5yi0zlh2De-nmoxsLIk5rA","UC6-q2TYBL2r2JOFLU0ElKIw","UC61BNz1JaCegSYfFT-RpjEw","UC61E_OcA4cIRrwxUNsFsN9w","UC61x5TuR7Mli_KqHvgY_AiQ","UC62JViSXZOJ5SBNnYmh1Ksg","UC62SdbBESu6qnieAl9uSd6Q","UC63Ywp-ddv_HtUiQ8V6zOqQ","UC63jjxbb8Id4_pdXGPP7aig","UC65r3Zfkw1FBOIMGy-9WyvA","UC67EdEAzslLij6-PHwVs_Gw","UC684lGM4OwM21gOXT-zZ-fA","UC69HcmxFTZ5p-Y_up5565Bg","UC6CLM-wyyRiC6gsO3lWpYJw","UC6CXWLDBrHYPlIFdTgXdilw","UC6CkYdh8xDNruNaU3CnZMtw","UC6I5-YwcfP5UqWABUEWPBLw","UC6JOps09lFc4QQDS52Twf7A","UC6SBCgnoGpFiaR0bQKM44XQ","UC6Y_vtwwHSxo2ExOr1NffXQ","UC6cgURF4vAvelVdG9pAa9Tw","UC6efHfvf6GtrupKJvY8bZ_A","UC6j-01gfxLHaVTCE_Sci5Pg","UC6jCTv0sVTr3xYnYHEbBT4A","UC6lbnE9AG8911VC-8VUFYYA","UC6o_zOH98LEjAr6DBn5eN-Q","UC6pzgnZ75lEnsOCLi64Vx2g","UC6rPzOWL1YVZtdqrzOHyCfw","UC6wavFkG80jQ63gOMKSPdDw","UC6zaszflbrcx650nN8fJ3JA","UC709a1JjgV39Fso7Dj71jTA","UC70DQ0CwrnE_ZVmNGLEcuZQ","UC71lCC0XcUJzwIFO-fdvMfA","UC73zrjXpIAD9F7HuD8a6ENQ","UC76Yi7qaOd1Er0bmlW65q7g","UC7A1bK8ALJ-oIouBCEGiPfg","UC7B-nm1wea1iKaO5r-JjgJg","UC7BJ7Pc5RYp9C6Ehtl4XHsg","UC7Bhpj_ZhdCN-tDC0KKDmoA","UC7FknUE25T8WfM6hW00suPQ","UC7GnaFMTkf1Iigkxa5CgQuw","UC7OTPg5I_imBN87m8IcpqYg","UC7RdF08O_4tGaiSvTe0TmwQ","UC7SP_Hb1cqUC2n_2uq0BFiA","UC7UBi3ueDu-iAngQ_Gi09XA","UC7VdHrMxFRvoUFhwsxzedbg","UC7Zct_U2su_rvoea63p7yUA","UC7hprbx1LzF_xDDlNv99lcQ","UC7izm8eMq6z_hlITssdq0mg","UC7mahiiZB_o-e-5zxv77HRw","UC7p5cvjuN6CyqyS4870FX3Q","UC7phaVCi8Gw4KseUZwyPkGA","UC7qYOlk6UnR4gZ_qyvw-hEw","UC7rn8CMg4TTU1CLx1eEFI7A","UC7tZMTLdxgvrn3D0GNFE5tQ","UC7uCiAkoRPglu2vPmsCCwsQ","UC84toramTtj04_CRFngpcrQ","UC85Vpoy8YMX325ZkRC7gDyw","UC89jKgV3efyzaszzFXwFGFA","UC8BBREf9rg2Xy3t0XdY2-ZA","UC8GUPLjui4jilKqEiM56Xsg","UC8GsLRFvGc69-s7T8uxh7lA","UC8HB0YfJgjuQVUHV5AhsgRA","UC8O0sGk1lVCZhoNzOCT5ZYw","UC8RKo7vg3mIhcjzT_IHQwzQ","UC8S4cq1P2RIyNpNfvj4buUA","UC8UJ257QoNKHkPoJrYKX-3w","UC8ZCh3F3zllSAeUnMt155SQ","UC8Zq_MdYiTfFPVa9nyRdJYQ","UC8b_LfLT1foLNRq2emBN5Og","UC8c2WphEubXh4LITNG1g2rg","UC8i-cZ6kadSiEHKEyWFd90g","UC8l7wZfLVHWWEwyQlFKSVnw","UC8pq7CJmPY-pt7q4Z8Qm1qA","UC8qX6KhPZzexpoJ9CW8k2Og","UC8rXDJsQ6JZkSWQ_mbWIsKQ","UC8uWLKkvAs2HgQW4CJpUh6w","UC8x7gk-T8x868XVT5i9Avxw","UC9-VqfGh8Oe3D4xXjStnawQ","UC90MVYHesf0iimKOelSnzBg","UC91X0kABY8n1wSEgkeztXRg","UC95lrvpAIWAmZgBMjyyHDBQ","UC98mMXL_XlU0L8Zry1ws4gg","UC9AfqT5TBDSzUr-FsKnKGHw","UC9ChlPxVi7sbjNHzPIfZrSw","UC9EdMFWI1j3dyXiBZSugVAA","UC9FDSX3cpiDBbL1ozzcAVvg","UC9FTCLzAF7zIKXqoEldFz9w","UC9GWbszXhHZNFy72D7mzfYw","UC9JAjE5DdxsBpPAVB5LSp-A","UC9LbGKrazp3qSLUb-f3ZKlg","UC9Lka1ooM3SqDC9F48f8PYg","UC9NeQ2fssdK0nzt-GHQ_N_w","UC9Tc0CCKXbYs65mc0LbkxPQ","UC9V4qSGvDV1TTba35IyN4gw","UC9Vdu3ONPJQKZIRF2XEvX0g","UC9XTcP9j_Y3D6Ljacjqieeg","UC9YW6dOI7Qt8rEIDzalD17A","UC9a69fBxvX-KpKM0IDB0pVw","UC9dtq9NYUi61r4wWmcGtA3w","UC9eac2rlnklg_bJBZE1N5AA","UC9hMZwngXxfXupodRX67mhA","UC9jr4Lj6vTkmIhpO8swjrkA","UC9kRnFzAkkKccEGq-jUdleQ","UC9lIqJz4BfU5JRWK3CeI5zQ","UC9qzpMGf8IevEgaQlLksyBw","UC9rd7iedEFFzcVaJUVZO13g","UC9skzWNKVcB8aATNKAzDMiw","UC9tQOWs-YJ0uxzExbmmf5-g","UC9xZsxnmsj_SK-l-xLadfSQ","UC9yIRz1YBGiqYfJUfXgjbkw","UC9zulV0IOXngYLob2QcH7nw","UCA1mipySffEVT4mTl1YFLWQ","UCA3wWELJcx_2UV-btdDZxYQ","UCA4Po7yFPKJ-qlR4WqwmIjg","UCA5V2RbjsBrNwcZ5FTekm8Q","UCA5vN5q4fAHlv42RmGUBu3w","UCA79gAlvNluMWw3Fa411msA","UCA9JtIh9puCoTAPYb0goc2A","UCA9fw0lUJ3EHUCI1BPrq6iA","UCAFaZuyQB7aTlMYr_L0KKzw","UCAHc7bgFWDqWOr-7T9mYGzg","UCAKgnlkPDIx8NuX76yalbvg","UCAMe2VDBY7UWNwOIF90F8zg","UCAN7u-mKsFbRqq2pdxwEMOw","UCAO7YdHWVctaxZND1YK3WoA","UCAR5atUz-wblq2VEqTzJWYg","UCAVuZrG4ns2r8-edtBwborw","UCAW51RvqK7sNRxxPwoq7ewg","UCAXlVFVjoQSi8suOKYNHjzA","UCAY-88V3uT4kuhjtnLrW-_Q","UCAYx1zmWXtSrZDJ23srOrvA","UCAanbHi541QLtts_3xFr1kQ","UCAdqRI-KDQPqFqxTAkSzZVw","UCAeBoePvPmr1JL7AjaNAs9A","UCAgtKgZqKFK74Ip38vZRCqw","UCAkRSk40TDor6ImwFz-NfgA","UCAk_JKqGBpWjT3wuQ36P8AA","UCAlYCsJGT4kbW4zIOFq046w","UCApMxoZrMPx7l-MGSmQU2AQ","UCApw_C7oEp80KS3Fd-UQfCg","UCArJQlXZfvyr3phfjg_8WbQ","UCAuFQ0Rjw8TxCAgRVeRofkw","UCAypH7uIMq62i8nntqxJZQA","UCAzGQ4n_7kMxAvZEUixqvdA","UCAzns_o4RYrGCvzmLapl2hQ","UCAzuyBalZireSV13JaJVtUA","UCB4_EiV9wZhhtykKTPsI2JA","UCBA55Nf3dWAv2L0jMaV6EbQ","UCBD9qbQ6pWlVTIP1x3M328w","UCBEfrx_jdEo4xN0CB7bklxg","UCBFYlkC2mfyv2TVkyDCwHfg","UCBGwtWF6VkuYUjNDjlrVNDg","UCBIkzr6DQx5YsWe98tI6lcA","UCBJY4aMK33aegMvygiJlfyA","UCBL5HXQhGWSUDO6j5YlKkpg","UCBLbx0zwDcFoKV9pdyOTuLw","UCBLko6Mu1wB1fW1lR6VUQrQ","UCBOUeorkYzY7eCYRJIravnA","UCBTdGh0OJMLwR0q7gIpFslA","UCBXFRaADbz1YqCsks3nd89A","UCBYJzk51LqV4v0qyIdlCweA","UCB_AhAVPOU5e8su_-a7cPBQ","UCBaJgiVNbjXEvhqUo0SecAQ","UCBav7jqITqngzF6XKyHwWvw","UCBehFOv7AwlmS9j-Gg6USIQ","UCBftwZfdW48kV5Ck6LoW6aw","UCBh6LI4YS5sMi_jWyXXzMVw","UCBkR20xTiAFTSZs9cGIsu9w","UCBnvr3HfnUKJGBu2vtG5dvQ","UCBpw_7nCMuWt2toUwUX4ZXg","UCBzcPT_rWYWc8za-EGnZ9PA","UCC-E1EmG-Xxc602aDMZscPg","UCC0cMny9h5NKPaLViOFVUeQ","UCC0gASrtr5-jxxz0z8H0mQw","UCC0srVg3egYjXsmsB_tmLMw","UCCAfsDBG1EhsE3qaMX2qRWQ","UCCC_ajcAiFsoIWogde8EwCQ","UCCG9W93jih7ik_Qi-lyckGw","UCCGCs7njKfwZWF0Nwm69e8Q","UCCKz4Xag4Cja8HYMdWvS3Rg","UCCT3_CQFvyZRVZLApjoiZnA","UCCU5F_SPpM9p2A93ihmDBoQ","UCCUt-YGmeMSHZfXQQe4XF0g","UCCXGk0Vh2RQ1mL6kNQPso5g","UCCa0dkFnPycxVyWhiJDc5xg","UCCl4jEG4PCVDxvrNNK_amAw","UCClGhFbEUF8g50rtSDamF7Q","UCCljhVGLp6tblIcdFZdqJ0A","UCCq3VWTcWfO5YMceojcGQEw","UCCqX-3o9SBf7Ml9VwkXlr_A","UCCvfY76VFF4tj0HDb1EK90w","UCCz40HVk2Y1UgiCzeF80EPw","UCD1kwbexWpMbXhQ1tkDKZJQ","UCD1rz2RzXDs-sFLpKGDd-eQ","UCD3Jti9aejKk8tOBzTWMADw","UCD5B7pCpQj9koB8EP9yMFJw","UCD69BZfnfHqbyOWOrjBdoKA","UCDEP0Sq1-BcOCEzj_BfnWLg","UCDEWy6viDg4pvDjH57UTDvg","UCDFD8g2hgEAA0u8uYqH4dcg","UCDJ5zB9zjQCqWUm47SxX5vw","UCDXNBpr1cocDsF5NFjRs7Kg","UCDZPZ50A_evLME1sysoZ43g","UCDa1HuJcRMBkG92XTD4z9BQ","UCDbHioKAxi9Lyy7oT006JHQ","UCDcEIUs0zf1DIWu4HbDRseQ","UCDcr8Kzr75lepvbF7rbye0g","UCDfOKLA5ZHaobtmMn-eEiMA","UCDgUG9vN7T45DGbfQMaTiBg","UCDiP0MUXFWdaEfpQIzr9Kwg","UCDl7YsRQSDmT-HqCi8_SeZA","UCDnHKK2EIHgF7n92h2mm2BA","UCDoKUqQNJGn4SnORz7NwyhA","UCDpRSwBREoPLltoyAsqEaOQ","UCDqM5w_dFv_ySidF7RiDzcw","UCDszbjn3JTLv2OwBzBy8EEw","UCE-KHuYDpCyMkAl3hzpXTmg","UCE1JmiJ3_4Huj1GhYpBR6WA","UCE3hk_HRwTW3qfzuEq4-pYw","UCE7npMVPTV8mVqBzvM5WfMg","UCE8OKP7HzoZHRilIMlGNVnw","UCE8ijn2QTZmuVEDSIoFwSsg","UCE9l61kVbzHn1PcHm_CG5SA","UCECM7Uez6WLjH1C-pKPwYxQ","UCECVsE7VmWvXkB8DAFfVQlg","UCEDpLZRbIEkPgbrc-xVibzg","UCEJopGuw2Ej8xsOH-J3c0Nw","UCELhSycO2V9VoizhHE1n3jQ","UCENLeqkiD88-YFykvYpz_uA","UCEPpnG6GPKqdt0zibkZRcMw","UCERkNdf0Ck6btT5l1pu52Rw","UCEUhNMbpmLr5pgAbTfJHVeA","UCEYo-rvS7gPRPjh9MJERbjw","UCEZT6MFAUiZ5V5gpVSV_oKA","UCEhHarETX220-6fP9wksMrg","UCEu1dP-gldJ5wWVt77f3OsA","UCEucCefU8Rh-cAStB2fxIvg","UCEwqE3jImi5-UWyPtedSpVQ","UCEx_YeqIPSdU2e6u4QPj8Yw","UCExhNo2w4SffJz9LvDQpOWQ","UCEzpZObez51nBnI6E1TQRwg","UCF-9_wjg_y48HSyhrFu1U6w","UCF0xP-veBt7N4XUxHQjCSIg","UCF2qf9eGZAWuu6dGz8AOx7A","UCF4dHo7Z-5WUYrXjPTdSLcQ","UCF7-ndYC-JZShpIv8iw9RQQ","UCF79v2V0um7d9zaPUZLJNHA","UCF8x1BBQBRlkdLUKaOSCqww","UCFBxvzQco3Aqwa7i5fz80AA","UCFJp7H9exizDhtgFOfYZa6Q","UCFKIOY8xGbhfZWBfzJavkGQ","UCFMSaZ5ObGhV1AjesmRiJYA","UCFQ_peVYIA8TiUesYrkC7Lw","UCFRklU1DMW0yJ1Dvjm7CWVQ","UCFTYjHXEQIR5kfa13ZPnABQ","UCFX-2QBbHe-kDDelrExk4Eg","UCFZ1iI2jC_2i7tKjTgpnIoA","UCFd3icVWPNf1mjx5aRe8Zcg","UCFdvY5RThwuGoW5rOL2veog","UCFeccGDOb2vV2pB7RA8VJkQ","UCFfhTi1VQLg3tDwMCJRMBTg","UCFfi2mMA9pqPsM9s_aDqXUQ","UCFgeCOvpMkvT_TsnAGHmP6w","UCFibgvxw43p4LQklipf5b_Q","UCFklRmkAJ8mmh6sU9h95dHg","UCFoFG8rE7rEAO-5nfUfVfYQ","UCFoJx0svfST7vX-7s_Ur-cQ","UCFq7iHWd_MXqt-UwhsyilrQ","UCFvtPTmRyFsJ1qYJ3M9vPiw","UCFymlIifBBRZFO50JJB8H0A","UCFzXvUKA-SKyCXLfITDykHA","UCFzg87qwuQTuIJpoSrlCghg","UCFzifwnx3xcrXURBxPe4gIA","UCG0Rhe077ceuNiN_zmmDwPA","UCG1kF-ifk8Nwgregy2i8TTQ","UCG35-mbCIqzQDquAzUScCLw","UCG4TCMncs9mydUaQ8aY3Zew","UCG586fhzG-K3t9znBk4lDZQ","UCG6K72MzU5-wlxdKN4aADpQ","UCG86ArmtWRdmoHulmCkj0og","UCGHGltUkJ3PbOYpYrTeKeIA","UCGKMsYql99Cs6fngDjOGq7w","UCGKxrsfDyg2nPVhcdAso_sA","UCGMCKrumtYOF5Wn4R48R4qQ","UCGQQyN3OL_Bo91ZcUynG9sw","UCGRkT7et3aYaDGmn--kEF2Q","UCGXj7nfpzTCYL6N_8btDYCw","UCGj-3tgbEGpcSMHKLF9mwyw","UCGmmJtUROGaU544A0GkbwHw","UCGnGi49l18HuwCjRgdMVXfQ","UCGo9CIDPYZcEv3Mr76_7kSg","UCGod2poiP4Bpoi41HqJxuZQ","UCGuVrMPnWVZj_pk_PZeSg-w","UCGyFXtUmlOxudVFQGZkYL2w","UCGyysMpFN8HANiMrkuIudHQ","UCH6LtfRDPQLUtsDaqcb6s2Q","UCH6afECMat_fj163S8VKe4g","UCH7qwNlmPg0GaIRCYdGkJhw","UCH88WOlHqWDExLWga0CjktA","UCHEQcLd2X1zRCn6Tv9CYZ2w","UCHEhnXPOVbsPwENiNmDBzIg","UCHFQIagmuGZRW7EPMhhY2Gg","UCHF_qtD6dLNdx_hIKwSE4pQ","UCHHXGWpe7XHM9FuJmD2ho-w","UCHHvwCAmVcvTtg6ZJ9gGOug","UCHHzCDwggFpCYS-QTchuNoA","UCHLdB0GT0s_DXp5TwTsCs1w","UCHLpVSmEOfVSG0dr_tkYFBg","UCHNmdxjlIW6bPbIhOAnuRQg","UCHQI87I7TIiw4iUOyTcLUmQ","UCHQIENvSI0HOLDYLfpgc5Kw","UCHRLJMdiLsdzE6XyU0WxMSQ","UCHS-LLwTOT09X5xtmI0_pWA","UCHSgq4Zt27CWv8mTWh7hYew","UCHZVG_Bqxk0if6N7SOgq1RA","UCHaH2rCL93YqAXzd1HMlqRg","UCHdTa-g5-4G6QAvflRsFMag","UCHh171P4OqRlK8BBAg0q7vA","UCHlRW4Kr8YUnYsgrg-Ic_2A","UCHowCRuEy5GBYLuptxflDEg","UCHs5kuB1KboWRdoKxft8nEw","UCHx3seF3OS5NU8nR8yH5BAA","UCI-6G39I7Wz4a-25Gatxs_A","UCI04htiIuAj0N5q23G3YCoA","UCI0J5K2KPAjHLHwGjACeRCg","UCI6qZda0nMQWD7-ME4jGUPw","UCI7vOPCBBLEVowD69oNTUZQ","UCI8kWUCGQbCVeXbHdEzS7kA","UCI9gFm6G9XhaXolrTZcvx_Q","UCIBL8hVbshWrKkFD6H3Uz9w","UCIBXTVTH_ME8oFpYEQjTlCA","UCIDbYQLRUy6niyIJL8IhVqQ","UCIFOicxAQ6rjLmRFQbJSwdw","UCIHxfdjbpxCQR0wASeSxpEA","UCIIJl9814VOaqxUu7MfP3sA","UCILyFL-XrjLkfhE-Kuemv_Q","UCINXoO7Szyl_AN5sO3iP64A","UCIOR0tWlHoM5Ysb3xstg0uQ","UCIOgDzzrTLF2GcKjEqSTALQ","UCIRlcbFsc4hPuPFXC2swpRw","UCIU7RUoxdFlHtzt6VZnUQHw","UCIWa-ByZhL8ZPfOz55jvg6Q","UCIX4FJw33LhscVSEhs31HNg","UCIe7sAVNW3g6bPMejtmJwKA","UCIlxXOEhjKRFcR6KfXFEoLQ","UCIm7e11ly4ZrovvbsgoCuyg","UCIpnN9NCsuOjlnDG5GYHJdw","UCIqcqlIygdr2AY7rW--yJcw","UCIxPnjE7GhhkAheuRYFNiHA","UCIyImFpXIavngILUs_pqaZQ","UCIzrDZh8odamQeVDnVsKjTg","UCJ-F9MnfxtpZgyxtCsJljRw","UCJ03FSMPJvYmau7KtkIWxmQ","UCJ15WcASjqU6RqqQLCFLetw","UCJ3DJGz3Zo1r7fERIAcvdPQ","UCJ4X1lZTJAzJgPK1GWKnEog","UCJ6AxJZKb-1vOFCeWih7bPw","UCJBSuFW16wh493dA7C_CeKA","UCJCjLepXoeHBaiTUj2OqW3A","UCJEoX9U146MoNouMWEBN3QQ","UCJIFwDVkHw2CdqoFLx4nlLg","UCJLfmIP__puUxUzPUWzZ6cg","UCJLvOc03UrAI_L6tMCkwrlA","UCJMGvQNUV5kUHJ5Wcd4lUBw","UCJR3Ye39cdQHYMPqsFOiF7w","UCJSPmalNAq2XprzkrxZ84EA","UCJVsbv_FUjyfVSxfn-3U3qg","UCJaqQDPsLSt1ERWbCAVsFOg","UCJiA9UdyRyrFEJiZ-4b6O4Q","UCJnuQv1_2mkT3xogEk9o_9Q","UCJrmkUwB4_wWTvcrVlAc2rw","UCJtkynSrJvNZ7KnJrIszlog","UCJurwJKqbzDJiLsFucNrqAA","UCJv2LVxkSIcrpNuuL0JD3zQ","UCJv6d0Gh4-YJrHAIyhYFTGA","UCJvhyfQFE1gZ3ReyVBsvmKw","UCJwhWXvmBxoCdVb9TSKYUSQ","UCJy7hLysK27ZejVlnpzxV0g","UCK06tbZmJCnJpQoW5ZmieSg","UCK3HA5kmeG36NUsn7M35DhA","UCK5xa0LYcq00-E-p7ubCjsw","UCK7umajl5XVdXMv-QEqGY8Q","UCKBi3yeS6x5N8uaskt_7pLg","UCKCWLj1o4475Du-IBvVYFgw","UCKG3lA6T9d0CidIGyOx59lA","UCKGP-XeoUxr42mNN_G5ytuw","UCKJokkg-kfAlj2dvZVLYftA","UCKKfnF6cnvXT5D5k2xs3V_g","UCKLvHrAL1tiRMvd1wwQAA4w","UCKQgkUC3KAS7pqpcUrc0nAw","UCKQjElmI6hGe7f1DLC97yNg","UCKUDAJ31c2SE4cJ-ENox7gA","UCKV-87lmIxwtHVw5zk5jIhQ","UCKWk3q1CayUSEZ2z1KEKfKA","UCKXyF_rGXpXWH9JZDRd09-g","UCKYbtT3mlSYpxQT1OaaJcmQ","UCKdtMlw2_BcuWx6n7GvX8pA","UCKh-h_uJK1LeUmrCTzYoYEg","UCKnChlqXSeDLZCuFFzKCWPQ","UCKpuDOdFXsk5JiqYSbWC1SQ","UCKqO_BD4BoNIdz7e_DJu8TQ","UCKuT7r4ZG0X7AD_II-xzKtQ","UCKxdPnjpFsR2bbkbfxCc05g","UCKxuYJs2bpuDYywQ3VWUgww","UCL-NfKbLE7DRTdWIkWuOSjw","UCL34fBfcNbnS1oPUN63Ip4g","UCL5-pYtqeK9QVugj9RyKrTw","UCL6bD3mROhlp0-IoFX37IVQ","UCL8FwUSGq2pcb8faKE85p7w","UCLBZx5xUPDeoGZE33N-JsIg","UCLCHpccvAfIQLCZ0TbINbcQ","UCLFD3sWWV3xpfZmhMOJ8kpw","UCLFM38um-Kuqd8d70aIeb6w","UCLHg0aVwdN3XRMW9D9LEo1A","UCLK5LeWtEVgDyYo37yoQHtA","UCLNKqWXF98bCZooU4lB_dQA","UCLOyjCkdIny1GZyCrn0KZIA","UCLRP8drXzWnQN-HUXxqklfA","UCLS9k_9o715R0kNCMyh85XA","UCLVilAQbTsTkw_j-TUVccKg","UCLXMdcfd5L8YB-Wx79mFULQ","UCLXsIy3piAIn-uwsoXEYezQ","UCLY2_Ame9t6npTXK7YgqTyA","UCLZeSmE-3Xvnpbs1fAkfSsg","UCLae-61QqIn8kqM0BPxGa5A","UCLdUc9ESYqK9pr91XGulSfA","UCLeF8jANVMtSfnZ7sVqd_-g","UCLiDiyzTsT50Jom2VeeDEpw","UCLoWnzrektJ-7mhcFxON46A","UCLtLHGXzrEzyUSeoMRDv05A","UCLvyTGE5o04uZUZ5Vi2ldfQ","UCLzHCgGCOmmi7ISagyEOXqg","UCLzIG_i0LcB1SA8VpGzVS9A","UCM3QjL8Mw0CfqoIOEJOqqkA","UCM3eJwl8o1gQXfi6r-rNE1g","UCM9dI-Hq_IHx9nl0qnBFZcw","UCMEEsoCtsPji4Le7OBpTnTg","UCMERRuVbp2lkCXSKFXTSSaA","UCMFU3CIJ4uO9Bz6s1KKLHeg","UCMFjkXSKXx2Kr2gugDbEXfg","UCMFkXdIlH9Uuy-4dKyZhA3g","UCMH6LWQJjTg0jJci0Lc2SHg","UCMIbFWOnlNPjcpBCNG7uAxg","UCMJY_-93ve2BkOxEYCejnGw","UCML4E8t3i-yLoQQI6afcxVA","UCMMHar94DHzL2Wm235KkuoQ","UCMPpGnODciQ7FawvqeJxy5Q","UCMRDWi7tyhcSuBZertFnqjg","UCMT7jES6_9ogXzPpLeAIQHw","UCMTMUcRimgveN2SiIISDOwA","UCMUSSU3u-k0_oVXP8lmWRFA","UCMa8C44q_M_6VhLSsFQzBfw","UCMdMynPHHgzwG5h1MQeXpPw","UCMdQmnncdHgoNw-9lSAYutA","UCMga6UPjQOc_yNCv4dtNB2w","UCMhnBkREf67Ci0nOxUL5H6g","UCMnJ5HsQJ9kXvA6PyyWJFtA","UCMnQdQLpSEWgV2rOJJXm-Mw","UCMnttz3GVbBAKw1SynSDDvA","UCMpEgIoqywSYKLeSmOLxVPw","UCMpj9syGGOMbmfWRPhCgDiA","UCMtBNG7Ck0YUTXEVbSH5Sjw","UCMvWB_4hh1_lKidO-7-hvNw","UCMxQVbyvwAGlqs7Plpie-Rw","UCN00tPp2tRfRr9GT04qaw8w","UCN11dPbyYDtxbBdfK8LrzXw","UCN2hsKpSJvfmHtZYO31nXxQ","UCN45hbpthuHWhtrTWiVWjZQ","UCN4rDJrmsUJ64UxpZfrN4Qw","UCN5YMNLxKZ3Cj7piZk2XToQ","UCN5dtXlRj2QLEmx9PmD6p8w","UCN8tyUC5G5-FDol6AytB6Gg","UCNBd7AoiQULiF-2VDQH74SA","UCNCUOKi5denQPQKLhZy2s4Q","UCNElC20etNL6xIxrPrRSuig","UCNFEkWtMrvAAA8jHUSfsYFw","UCNFmCwe0RfTS8IdqCupPvpg","UCNGYMCiL_4HsIwWjAwcIqfw","UCNJ-QjfQiYEUn8scMSQA-_g","UCNQ9Cz_JHgL4OdsoJyNlb2w","UCNQDQB49qm7lanmagtRklPA","UCNRTojYx9VeR7K7vBRHoROQ","UCNTahcHwW307OQclT_bjJmg","UCNVYP5kYsjkQI3k9aVEMtHw","UCNVoXEtFpnn7i1CKzbnmlUw","UCNZaVGBMWbMraTfV-I5i-rg","UCN_D0wuBscB2xz6u46DN4iA","UCNg47QPJGbDFUHdu3Ps4khA","UCNhhFoJVnG0uOskq34LGbgw","UCNiEfADS7KaAhcxfeqLjTeA","UCNkkWKq1EbBozzEdiOq3-jQ","UCNlQsg4egCnn6MDh-GRg06g","UCNmLeoMJ8rnr8aoo570v2Vg","UCNqWD_BrAn04vMiB2MIoWJQ","UCNr4ujQ6s27G_cQXeO7EZtg","UCNtD1L6OrAyowftCr3KZxcw","UCO-3jGxflUzZHCO7EbBS5NQ","UCO3-VeB5jqOz94vp5I4Qx4A","UCO91oRz-FHrl37pOJO6kzMQ","UCODLRi4CDPZOUnS2oaXA7EA","UCOG65kUZlHWpCsj4nVwdbPQ","UCOIvDSeg5SC5FrfWeIk9H3A","UCOJnqjKi2e2em3Zj5i8mTHA","UCOKhZKmksFhRXblkKYDPYZA","UCOR1fWf2gOf6OAIVBgV8JqQ","UCOSyuQFs17PugCgmcSPBOYg","UCOTult5ZKTL0AYl-DMpIclg","UCOVBxulhyp2Dtr1Nx3WiPCw","UCOW_mTemviskUKauxtSurjg","UCO_7KcTcOLEhrVuSFHL2DVw","UCOad2cpsI2gtLWhY9DTS3cg","UCObAKD6LW8yr6KtXTRq6oFA","UCOlYtqKtS0O2QVdbRkKVdkg","UCOmlUIoeaDpmBA1PJw29E9Q","UCOs-UU2LJxGgELQKjUXmmgw","UCOtvA2ZMXwME26K1t6OqC0w","UCOuq9flIEf09USDwhkQAX5w","UCOwJh_82AmqBtwZTiCuDPyw","UCOwf18uD8nadOM3wL5Il8bQ","UCP0q7VhDE67wYCVvliJE8CQ","UCP2Bh6GNHOct2jJ9K20SBXA","UCP3ABCTzgGu6g2N9WrA8nKQ","UCP3SP_Bv-9RmIpRFVKCwJDA","UCP510uPkmRnrHLDEuDLDxQw","UCP7LqnW1n886Jz0OTSSqmpg","UCP7o5rJHsDEpUznkTSmW4eQ","UCP9ksHRzOBPTm7c94lvMh4A","UCPEP2j9ksNFZOTF0ZkMbrLQ","UCPHeU1xHL7NBIie7e65e8xg","UCPIiE-beDSCJsUv9la60nFw","UCPIpnrgSQjUKP3Fntr8EMWA","UCPK5JEfPiPtI4Ep7UzhvKlA","UCPPf8qqiJVeHLUQAkcB47jg","UCPQxkVBU-k2uVwwKQ2eWxBA","UCPRRib67QkuacGfP0BN6ACA","UCPW_P6zKx6wZNTqgFdfXwtQ","UCPWnPM2F2abVCO87qywOonQ","UCP_1TbG2JgaBAFR1drYtrnA","UCP_IT0og1WTPW6yAHclf9gg","UCPeHcrvSwkthIr3yZKjRIQQ","UCPeLsNgd9C0CvdJk2kDDD0g","UCPf2-6KgbHFP-9Kj9rcGukw","UCPg16JZRLKtA3NYtDlrfhbQ","UCPg92Ium7Ch1BwnxZJdciFg","UCPiVOBdjwXMNxkg-azbwUDw","UCPnJ1JCxY_PuD2E4gbcFVWg","UCPtgC6f--ND3699VgpCcXUQ","UCPvkjMYy3rp5iHDCbfQjOog","UCPyFExL7Meho8gx6gRgA7rA","UCQ1Kd2MILdEeN6Jx3Po76xA","UCQCxE_EeMenULORYJhami2A","UCQE8RLL0wCF1ZS3wY8UCeCA","UCQEdkKQKAD6E5JZtKvF3J6w","UCQJ3cz8wnvErXgBC3QvJ8JQ","UCQK9LmgjiBHh122qjDjCbfw","UCQLF4zWFAhKy8naM1TS2JMQ","UCQLUGtnsI882ZbgfNrcJDzQ","UCQONa5ux0mNY6sRxwcNEzxA","UCQRKSR0G2kCBB8Y_-MXXFJw","UCQSxt4Qzmq67dfgRVr6b0yQ","UCQTWIli2el9Vfl8hzNfxtjA","UCQ_7rWUyUkhT0_DJPMpWoOw","UCQccbTeyBZd_UYMxmnl-HwQ","UCQiHnR0sXhZObGXj22ScrXA","UCQiJscQ25vxIyiMLnob7RXQ","UCQjakSWSW1jimR5ywP2uyvg","UCQmpRnA2huQofyWMZlfiRZg","UCQvk2rkB3OL1NIy9Ay5LsYQ","UCQxOuC6X8uUeya00N33mtwA","UCR0TKcCGAm4MO85blOn-HRw","UCR25apD8K641dhzQ7oysDWQ","UCR2zXJDfRTD28qypPRl05xA","UCR45TMTAJkH8aUs4hGb7t5A","UCR59nfoFA6toigyNyKkrlNw","UCRFmSNAjzayGTp3uZ_SWk0Q","UCRIu91c-AiO_wO2s0MBB2uw","UCRMN50UCzr34MB0SERIKEdQ","UCRNV9n-XVhorVleKRC08BPg","UCRR76Kuo1XA9azUkG2pYdEA","UCRSe0F5j5yvkN9QHHmAaDKA","UCRUPeFMCy1oP6nD7gQn_Q2Q","UCRXv_lOaCCzUZuFrdyvu0Yw","UCRZr1xp3KGx-_UyQTIyOypg","UCRaCDxBTNEofCE-0Abi7JXw","UCRab4b0PZxJDI-2hpce6tkQ","UCRhWeGC2jiKSuf94DvdylLA","UCRlQ06lpgpd7r9ma46yvlDQ","UCRmiRD-cyFkrYlaEGsXwECA","UCRny4ImR3qEp5Zg-GnTq-Kw","UCRv0hcLrDb5hK6DhtPhFj4g","UCRvD0gRKFX8k-6cqKftIuaQ","UCS78-HvfUSwlw0TGzx67OxQ","UCS8vJakLvEU3nQkgyy7-uKA","UCSCbalz73IcBP3atNmBavqw","UCSChFOPYj6NnC3GvpuJXCxA","UCSDqfwPO3dS4FoSB8KShMyg","UCSDrDDDyTzyEybNYWWii5Zw","UCSDznvhNBcwvAvJ5mawhPzQ","UCSM9fCxLmmzg4AANJ4TzRww","UCSMmtYGahweOXe3zTbcDlKQ","UCSSbD3joJNODWD9dH8H7wew","UCSSdVoYUKWMM-opkzlx-W5g","UCSVGk6QAlTAFmA1txc7FGWA","UCSVsHDPwkEzUxamL9unhI3w","UCSXpP5zGjSwsBwJEQULueBg","UCSi0W1QAOTkKuHT_nWA6A2A","UCSixjb9zQLJ9yC3szrSFjzw","UCSm4KtU_5BZVXOb8IMKzePA","UCSo8bJxVwMj2nl7WdTlNHpw","UCSoTaA9wHS7w2eOcGqCf8vg","UCSpdEzA9pufATr7mXQOt-EA","UCSpnQ2N0W-Gon4Ne0MNrRPw","UCSqPPDNai_jHUGpzLBFS3VA","UCSw26qVXU7TU0UFfQhrBFhw","UCSx77pc-riUb_8pY0aQnG9g","UCT14blOWgzAT-5ggXC6K8iA","UCT5neA4IWLxS4G5cz13MY3A","UCT7jA13WQRbMtaKYOnlVyRQ","UCT9hI949-auMQ2zojKDVybQ","UCTBLAkVOj167Q-NAoXhgNIQ","UCTIQChOg9POJPAGOVBRoTHQ","UCTJ6khbCtVzSAUwFP6UimiQ","UCTJZXvM2Ihaduj8Gard0DYw","UCTKwfmu0nMOximU0FXI0tiQ","UCTN6rFePwjJDeCRrc0VBUpg","UCTW2ld3bzN_TaM73X6L8sMA","UCTXrgWtYVSzGe1HmvUYMGGw","UCTaxffbC4C7l9SOmHSd5fKw","UCTehMuOeS52merknMMpnuOg","UCTgPROVBqAmzb7G0QFeDJLg","UCTlrQ5SwwhZvZID1KRMJFqg","UCTs0FuMnbKH10pjoKGH4qlQ","UCTsT7irY0bbwWwE9NfPQ7rg","UCTtE66ZgAr76o3KopcxG8pA","UCTvWpvjy7jz8cD7voTWNZkg","UCTxpd1fkM-q_Dn5d5vNejWw","UCTz7avm250CxVPbMNTKpH2g","UCU1C3EQb2e4UaXOpmBuramA","UCU2lfeul7_ACmySTvtiaytA","UCU3YIvAPNMN5ih8M8ApG_ng","UCU4nISm8RonP1nzuUuqrIPw","UCU5YkXUZyxfmvFM9HVuWoMg","UCU7NWlylD0cDoQChdPyJDdg","UCUBRGnQGjeYu-xls2ZTQ1kQ","UCUCfs5CthsIdn4uYyu1b5NQ","UCUG8r4iNzvijzsP-Bcipb0g","UCUH7fHv24UoyA2nD8Z_CaDQ","UCUMaPfovOWUbivGUTJe62Iw","UCUNEqyRgbbX2lcHgGcgvisA","UCUPk5CAQCcvw_fQwFFRizYw","UCUWRrRcm1gYOpk_jK_svp-w","UCUZPBnupSjtW0mlx6I-v_Hw","UCU_HP5pV9-de1vX-3TqqeCA","UCU_N-cVsQmkcxoGdyTnYA-Q","UCU_ho6FCzR2l0e5fFwfr1Dw","UCUcJUpc4UE2aDB_wai6DQfQ","UCUceCVOQDvVAeeFr2uxqusQ","UCUfY3t4kJdQmV3nuJeXZYew","UCUfi3V-HuF3wujnYo7wTyJQ","UCUvWUmYSsgVMsTyjJw92a0Q","UCV1n5IFUeoxU3rqjHcwezDQ","UCV5KMPe6WZMJKbTYPiUQPUw","UCV7oaO16neOQW4P6wZL2wog","UCV8idhUKAEGE_FQdZRO5DVg","UCVDr_VB68eO29f9h1IzjAKw","UCVFYjr_EA7f2hH0KeDAEjhw","UCVGb-_2022jmtI_17grifpA","UCVQC5BXryzSD49Y9MEFHchg","UCVR63dr1OLcCLOP50h-qw5w","UCVXe6g6E7gSUcyVnJ3MrPOA","UCVZIOf-Rh6eiFx3-0K3_aQA","UCV_13zk2cC6T4C0m4xuMKjQ","UCVd6ml4bNqejx0khftXeBGg","UCVdT49sDjBAIl8znMbNb8YA","UCVdmtPzVnCIk1tmmyhL9Ecw","UCVhacsgQyLmqrujmesLpI7Q","UCViQPOUCFGELEESxj36HF1A","UCVkSzh8oDUelZbNs43r2f9Q","UCVvAD1H1HOJ3Bn9h11Q8XIw","UCW1SVZV4VVsKPabIT9i_oyw","UCW8tJuHMRbShSjDJjptYalw","UCWEWsn3u8KZRlALE6arK1-w","UCWGqtI29c8A7urrnsAoPY2g","UCWJGWWCru1kn28cjAtq3LsQ","UCWMrrV9ysYQ2vawzzOeXz6g","UCWPILwu4-tPHSl_O43J4lCA","UCWVynxQYOM2M8NYaZDPotJQ","UCWYOhzO40qfQPCKNqtjSGbw","UCWbWzDkRP9H5u17onZ6-C7g","UCWcWPP8-KoDeFlHuIiDhzpg","UCWeltKwsRYhN7F_aQdln_vQ","UCWfG7ptMOMMRC6nipNjlxzg","UCWi17oM6-2GyolVIhqa3KtA","UCWiX_Kx_g7awAdtnnq9as8Q","UCWlsnnFYhaGcC2hW0KoYgcg","UCWpFr_nL48m5xaAyBKrFizQ","UCWsaUbzYZNowDw_9Z_DeU6g","UCWsu5zAR_ah_c8KZ3WHDK1g","UCWtCoZazC3-E33xrXVsq-JQ","UCWtFLESMAgSBvLQ07L-4NFA","UCWyfITM5gEVV_nDCkCPBlPw","UCWztHippKNa31qlfPZNv6sg","UCX-wpv1L2thk94lZkTbvNlQ","UCX0AfKiVJds0NvotBVooHww","UCX0m2XUoIPAb32BFMc4yvLA","UCX24bCP8kUf_ibLIW15bBuQ","UCX6ncBs_iZIsOqYVu5Qal2Q","UCX8FGF51PtEi3dc275fssmQ","UCXA9pgQ0wUUYoVhyr-ZLBbw","UCXBiB0Y0alIJ4x_r_SeAkuw","UCXMzvhZWZAwAXhwv2QZheig","UCXNOLTaxwV7yGPI1G0Us-0Q","UCXPGNLBNND1poWmC4q0ivmQ","UCXQE0yU3niPaKj7i2ofIKzA","UCXRo-FBmrhqlLglms2AuE-A","UCXTAcPk7OuiwKhKdS5oCXKg","UCXWO3OiiUGeB48WUyGuLlJw","UCXX0iCrVQnlNvGW4gKEhHdA","UCXXppgnB3YkNGI1xw41PGFQ","UCXYvBPLhr9iMmckuBf2qJuw","UCXYv_Cq_iJ0jsqeksideN3A","UCXZfoiL_EIFB1FqJJELeX6A","UCXhdw0WpiHTZONJJuZFhgug","UCXksV5mf23KwADxovOxqDXA","UCXmX48OadwMuC8QhMZ5U_2Q","UCXmwz9hVf7DRgQpHahklkTg","UCXsQYyFMzTnPSOXqSv0kB7w","UCXs_knyHZsGENJPfv2K60Ag","UCXshKXs_X7Gd5XDq7x1YTUA","UCXtuJ6lHEBLyZObDIDZa1qA","UCXwXB7a3cq9AERiWF4-dK9g","UCY0UMcIyb4NcgIQmom-T4Ng","UCY0tP0drkwwbnuOM4xMIdFA","UCY2y2uthN6J4SRxH1_NdB-w","UCY4TL1sokAfrtBs67plP3FA","UCY7J4wLGEfl-bAUmUGrdnBg","UCYGhQUzWy51DvHBoQEj6hjA","UCYH4RGf0_EhLO-rd8JajjWQ","UCYJVpn8IlPu6xhk24I5imgg","UCYNJ1MSR_jeLOBxYu0iDWyQ","UCYNU6ln-YR1bO3rYyBSrVlg","UCYNU8XaS0Mev28z6HYx9_hg","UCYNmT0-kxaq40fX8LXxNL8Q","UCYO3ortnOLM53bCY6JgprRQ","UCYOgIHKN6wFnIhYQ4T04vNA","UCYPIaRh63TZg8sJ0uAmtGsw","UCYPYuG8OR6FPF8rEMGW3FGQ","UCYQgWRheyL9VCgj3ZktLJSA","UCYVJ2I2TFcJ9xBv3ig6ylcg","UCYYGVp3-NhWHIrQOJ4oiJ_g","UCYc1_hZ73Lg-6qT6UKqAibg","UCYdeGq0k2CS86iOX6WdTqBA","UCYgjqy4ZKPZpHfVaIUT0v4g","UCYhx7RTMGXYJ80veYKBk01g","UCYhzn0FrNjpeI9WV4k319Rg","UCYm7uphUFhV-nMbhuNA-b8w","UCYpTauy8gt7kyFK9yRqDMIQ","UCYpxGeypGVYC1l0BLlsGeIw","UCYq1jU7w-IIySHynAEwnxlw","UCYrXyHEWJbGcjYIwzO1RSog","UCYuR4ZbNWKn_t3aDcC2JvJQ","UCYvQtponLRta8Mj3yXyH5AQ","UCYx-mu9v9VRkmCz_ySCDmMg","UCZ-y4SUvhGTGM3pSYWbW6Nw","UCZ6aivUi9Tqi-dMLI2okmwQ","UCZ6y1-SbzaL2bxgNDsa6qmw","UCZ7cKwb4pq-Ta_sMLy92eYA","UCZ8FD1MoTx5YebcvWRZbrOg","UCZBAVQOlKG3X5vZ67AmNsZw","UCZCQGQjLZgzXNlAC4lBR8XQ","UCZIlh86OCDBwiAqf3rXrB1Q","UCZJ5ZrnRYn2PtDd0ofRRqpg","UCZNgPDux20C_L1ZsthJGnew","UCZNgY3OHTEciZ5IrBnB5_vg","UCZOIGQR-n2zNnEVtJnoDjzA","UCZVeToN8sMbPcO2Pf72Ry2A","UCZWxYb5LBLqCjCeailkVx-Q","UCZYy1NV3er70N5Dkm1NIZ-Q","UCZeYfBUs9fEwiNFygRDZdrg","UCZeqVK2THE260g9IGWSg0xg","UCZfurXATSFH6rb4PXbtVx6Q","UCZgSUe6u10rj4WV80yDDMlA","UCZiPRTMRMQLWa8ZRnR0vDKQ","UCZlKSc_FsjRcmsBY3iL80Sg","UCZooJ4IwhpcIaqiRvt6eJmg","UCZp7_dxjKsUSO2C0oNiKI0g","UC_0tiYWJsNvVNzREaJIg5NA","UC_1H9S4KyKZ0GrFh4dK_blw","UC_243EetKd3QLwjYFDiY8bA","UC_4syT17DvSSc8wGpxc2b1w","UC_50JVbmDrlJXhL8gEXxb0A","UC_5hhkIiFIZKkzjqiW42ghA","UC_6vB9w4WE67SaBlwBw-fqA","UC_FKn6yK4Yr2KzCWwWdXq9Q","UC_Fa8qorKVNimhxePTcSTeg","UC_GCyA47QjZ1RYxf-dmJFFQ","UC_HC5Yxa2fBeAqF94_MzEpA","UC_MrLJlyhe3JJwmh9Vt8TEQ","UC_NXAIFyaCLRZ5PQe7aTvJA","UC_NYftIXd0NU5EQr_5Pl5Mw","UC_VzrfoVB9DqwazUboYO78g","UC_YFgrt5ZP3zGlxoS1iBFog","UC_Z2-gddDX2EjIvgveJpE5g","UC_b2V9Gzb5JCwrkQBRQ72GA","UC_buxyXFhrMnSpP3iUupCdw","UC_cLMF0SZCmh1HKIQHu_SjA","UC_d_pUg-RJq302jqHlYvojw","UC_idUuicU8HrM3TbpMCKeUQ","UC_j1KpD9yX3vHGNWGWFo_AQ","UC_mJTYdR-A56Qk33w2XWvdA","UC_pT_E7LJeU8JddHZQIYm7w","UC_uk9p_DJJXi_I5QAwJyRYg","UC_v4OZGHOWdnAquhBdmdPGw","UC_wBNd-3amxDSadEkOdyXOw","UCa0g7OV4wbZ8NMvGmWZcXiA","UCa1BCZE6xPaJ7_AKzi6xRfw","UCa52Z41daD5B-qDzju5mPsA","UCa6SUWDFVQwik1JyWuGifBw","UCa7FiWeGKeUIyCn9ere-Ubw","UCaBYvRPeFJMB7sZLmGUR8ow","UCaBksqlyDF8trI_YgqgvFDQ","UCaDIKLqn2N9i-VqKE_0vLDQ","UCaG6_UbBoZ2EQwiqoKX7ahA","UCaKCvLnjL7aF86kNzETOgTw","UCaKFRX0Bp_ET4jd4NCWGp3Q","UCaLUkbusSi-NfHw1K9miLRA","UCaPu3myBDpUCG957uxb4nrg","UCaQMDWeBzcVVut8zw6B4k4g","UCaQOhTmF_AeTO5hCamyoc-A","UCaVZcmDRWHVG4KrAJrSuIvA","UCaVnNvP3YONj2wFMZIoK4Hw","UCaW7og8GNvsGp0ZXRBmmN5g","UCaWD-Pvcb9PjkBMOti-o_EA","UCaY7MFjF5AFS0cJrH9p8ZyA","UCaYVAh2v-Pqp_MupkaDOi_A","UCaZRC8TT97G8S_hJSarsbTQ","UCa_TyT2aspHUpcISf1p7Edg","UCaaIpAdAxqnIiTqXAdTsjGg","UCaadj_ZscWc6NrhlgyhgFhA","UCac6ZKhQ8HizcoAamyw_RIA","UCad-_WH6oQ38mjCdkAnLe5A","UCafnrCtIq1ro3EtGZLm0QAQ","UCam-KGmfi4uIJj_kDScJMNg","UCamrP-g2Y-JQ6QPMwK5aReQ","UCan962IGD_cMPJVY4lthO4w","UCanuJsxsWOPZdmGYsN_qk9A","UCap-jz4zSA1qlgUS32TkN0w","UCapmRYpilr0qr_KkKQdz9pw","UCasD2E0X30X3VPq5lhQ9gqQ","UCasY2emDwOYJIlcuBnNsEdA","UCawJZyby25U7AgY_WL2bfJQ","UCb0tcYCri2b4bUzTJ5_84_g","UCb15FZ--n3OQrrloM8I592A","UCb1HGHW5xD-y1KoosL1FASg","UCb8sP7FNQZMa2uxcdS8H4Ug","UCbBtMLv6KlDqBLXmjkPjorA","UCbDiuWFi8vGXPJ0Fbyb6EaQ","UCbHNfsBidzCBCa7dtpvw5qA","UCbIAh5AHp4H3M10oiOnkDAw","UCbIoECsVYJo4Ha3IGam2giw","UCbJLZFdH6iWbdhcrhSUHDGw","UCbOXh-DeNeqHujTNPD3DlWw","UCbRwrOOV-zoI24aB0HyANaw","UCbUXu3ez5n_ec8eivtKQaGw","UCbYt7L5kWr3-0V4Px77Dvmw","UCbZ4zquP7qj9znreEIsapRQ","UCba7rgXe2ulMIcMWKlc1ElA","UCbapiN5pkD1h7YVaCkJdOmg","UCbfVbAGlDWN2mYEd2fVBTrQ","UCbgtkbzg4EHE6ggcsFa1lyw","UCbjHL7Gp1s8IYFmCWB5bMCA","UCbooZ3JSYXd7EOJuCSbImOA","UCbpWaFigAp_hJBT9LxzfuIw","UCbqDO1V7AdC9Nl0dD9HXedg","UCbrpD0W1I9MxlX_c4vAGBHQ","UCbvP-5xqD6huYqUK5KQHtVQ","UCbzaKyQ9AU-zfHSBrmgAf1Q","UCbzu4d1sGosrn2zos8Qog_Q","UCc098ks8vIxe25fX_GEAWeA","UCc3D7jhl3zP01Zeqt-xw2kQ","UCc4NMnPQGYqhfjQEnvcmnwQ","UCc4U3Ly4wlFsCzoLvQDPErg","UCcC_c8VWH4VhC3-XrJ-SQbw","UCcDV9a3R5OzFMcXfuOfQ3Dw","UCcFs7XdD-4itBYK2N_CrzVw","UCcH0SxDyzKFa4Hl78XxS19g","UCcJPmdgEyHA3jDtziPLUabg","UCcKXnq__wjwF_kxD8wwELkw","UCcNukKWKRHlHsKi19VRDcuA","UCcRFeP_un5fHvlnO2bGSoNQ","UCcRX3OjQuEvdLOgSXCoW4_A","UCcRgEk6MhUIB5cycldgNgGQ","UCcS3WKdmuOIYvbCpRLHGkLg","UCcVYsMkRsQtVJM7nxnhDTOg","UCcYug13KpJWNSO4niSw8lAQ","UCc_92aSX5tK5IGMC0uJdLtA","UCc_N1-s9udstEUJ0AlWWlDw","UCca4lcB6yPNscShPuB4Argg","UCcazammrt-b8anzCk_3VCiQ","UCcdO_VXsbc839FOoWxSUk6Q","UCcfeX4nFZ-D86edR-VNK-mQ","UCcmkivgdwmypFxA3ffNAqpg","UCcr7IU9tGgr4Qg0zFR4ZrfQ","UCcr9NxSCTR82O-hAWiqIX9g","UCcud7asX08Dm-vVienbPPDg","UCcwxfrb5zdkK5NBoY92bGHw","UCcyUY7QZSOHtib3Sq9uLpqQ","UCcyrXbT93ZLSNOKXC6eTYsQ","UCd1Lhd1VcGLGS-618tjwIXQ","UCd2H3z-DnQRrXwhoTD2NP5A","UCd5YluDmHBpKSPiIFVl5sOw","UCd6OKVhO91RJm6MtPEXMmrA","UCd91OkuFgxYClIKzndHHKEQ","UCd9OpDsSUuT2aK5CpPJUuvA","UCdBoONh4y7Lg2WyjQ-qWRAQ","UCdJdD_1DwYQ7wf4Joi28MJQ","UCdKYt060DH5zGYGGjpu8XZQ","UCdOLaDzAaySwDSWlvv2oihg","UCdOxN5gVNU1RMGUh_W_fmDg","UCdWXr_fafp7kuAtCvBU5U0g","UCdX9yt4OXPhQGdZ5H7Ie2Ew","UCdYZ-6V6YEwwz9Sb6YBuFXA","UCdYlIAH-WUYLuC_X7BERzww","UCd_yO4eBR_xRwHZwmiptYeg","UCdc_kLSYI3KDZ8EbH_4Gquw","UCdcjsMXX4OPgrBrp0pysM5A","UCdjfTA0-FYRgpg5plT-grpg","UCdliutPInkLzAst1Ql14CVQ","UCdz6NUzVHQ_ClZpr7uMU-gw","UCe-5FUfxaGtPf2Qc3MU6YKw","UCe2vzTbDkj4WGMHMzDewpjQ","UCe43BnyvDhgDCnYdg3s-Clw","UCe43r4SNZvNA7s9MKxi1O9Q","UCe8tZHYCqPBGLZDYXyMHESw","UCe9i1O9X9hnCaapZnblqJ4A","UCe9oMSrNBHkHCPkz5pRPerA","UCeCnRTfuQ4t2fLkdD6VUC2A","UCeFOtqWa_J8ABpQeqG2_kUA","UCeGzRxGW6AKGUEnodr9Ooxw","UCeIZu0RwLSxrmH4NrbOEEWA","UCeIultLYXC7uAkpVKCv17lA","UCeK3A3_zVFu-7EVkU2jnnGA","UCeKXXs1A7EC60_AXoOl1Hsg","UCeKaS7QUlVkj0jKHI-v8ELg","UCeNgRHpH7OHZetYjC5JZXGw","UCeR1kUSwuesQ4xzTsXe223g","UCeSxi4rgGSKp8PbED2Lbf9w","UCeVEDxia-EWgq1D6X0ub1ug","UCeVFaGrfnPVMzgDOSSg6Pig","UCeVs6S-ay4PS3WIHA3w2M7w","UCeaGpNpKkTcu1paQLjcz5Xw","UCejX43B01hV1c13MJ1SDXTA","UCekYMVXleGr4p8rhggmKgmA","UCeloZGbkOGbXeYPkngsj5mQ","UCemiT7pGHOo2IsXlhKWAkxw","UCenqyq49Vtk9JhPBtDLLtlQ","UCeqRlb1s3Q9J5umTRDLi7Qw","UCeruMnKb4tlcJltmsParFHQ","UCetv_WiqFRTwIcaTHm4GgCA","UCexZh-Di0SiINp9y6ssbU0A","UCey8WQxq-tvwTbvis3InqFA","UCezXJndWYi1zfla2s2VGbyw","UCf0WMgvYElbyt1zD1Ip1JHQ","UCf7rP_VNViMZ2GiNX6HNAqA","UCf9gTTpF6fDk6WDTQdOeObg","UCfB0jzs1iVL3jeUb_CgroNg","UCfFy6upHd6tDfjqjZJL6kpg","UCfGQDQBHGxgWfugiujMIs7w","UCfK2PjdJblLbRBgj_AJInWQ","UCfMkXuLWAWc41Lp06ncDcMw","UCfNhSgPm2o7VrJDvSxCdOdg","UCfPtYKhBZ_GIMNd3QTfa_9g","UCfPy-GU_VEdGuwmTAs23AEA","UCfR0jUUdiGAw80zTQaHrdLg","UCfSAz08mhX-dF1Fp3HJX-Hw","UCfZk17mjb5SWSOagoIBxJ_A","UCfdZis8qrdVK6LPYFxDtc0A","UCffnnPCfUQyjo8zplnP79YQ","UCfgbCPoGXbdsodjxefWuqXA","UCfie0uYP8OrUwzL4y9UUBQg","UCfixR_l-G_jlFBXhE0Ey9VQ","UCfpYi1V1kUUmcyuHhfeBvzA","UCfsbhgUNAGtrF3R2cd6dzAA","UCfuk2vR4UD-dhmaELbhlUxw","UCfwTOFUSRNiymHt5Ua0kkig","UCfwVnTDdQ_DnqUBJnA_fzLg","UCfxXCwQUpOrQgc-Rcyn4odA","UCfyUePLk-r2PEKNNCpExqOw","UCfyb_zTHf0pdCFr6Qtc-E2A","UCfyfHf05oYN0LzTZPyyWmMw","UCg17YSkWpOKoxrCoRZRH5TQ","UCg1Taob4TbD9bcgAMtgqFUA","UCg4rN0J5GqZogFGE4jq7iTw","UCgC9tf6DOGIiuXtmCxz5OrA","UCgCYL8LXw1CppL6fed1TiUg","UCgGuLF56ec9qI27qtwCP73Q","UCgHpDxXZBqkiwTgHUOPLj-w","UCgKWKmSOFcZNYvzx7u1OUag","UCgLHUSvHGwFvl2xFWrZr18A","UCgLq8OT0dWA81-p_Nt3sxyw","UCgNJjEmrl5O0F8gj-T_dcKQ","UCgSZx5cNtuZGL7L-bvfwTtA","UCgUlGf2Dqv-ed7YLFBzjscg","UCgVck2Sys071iRz9N6DtkVA","UCgXdje0VQiC92kpI70EcpmA","UCgd-5Q9EFBERvy9QAyP_BbA","UCgeb9-ip5YB9KZAdvQx8GOQ","UCgfnLLxdJ6vxMuXZ-d3v4ig","UCghyIYXTq5skVxnomyNzBXQ","UCgoSozNpHbedjX9H_edD5uA","UCgpVz7N36aPHF3K1n1HbjSw","UCgqtEPEwIV7-zePxaYip91Q","UCgrnrzG8hJChvKOM6GXCleg","UCgw-735MUN0Edws9HwxrTCA","UCgwyekNYdYHf9oCCO_rUGDA","UCgyDbH7UI8D40f8xPHu4UcQ","UCgyc4wYx7aiYdIegZf5Ry5Q","UCh-xb_khxF50FtwXH2_GXLQ","UCh08rpHzS-DuBEUH9vQUl4g","UCh1h34TrUAVn9Z68YYWzZOg","UCh2mn_1Tu18eGVd5kpXccaQ","UCh4IoI4IITXIuQ1LpivTOlw","UCh8z0-GsB-acW9_18SR5kFQ","UChCNWKcoaaSXtAAdThFLRLg","UChDmgq9jLgUW5Hyw1GFlTFA","UChF_j1-kxy2LOBnv3qgqu7w","UChIzm6gWOGC-bqnuJvRPm9A","UChRDvjHyZvNgQ5KT_Mv8GZg","UChU47_wH4iBnM5-vEgG6RgQ","UChUSgme94fxvBLnjdyr1PLA","UChX2YFdk3Tbt_ZQWS-1Ujww","UChXp6k4LFWO5iqQoiR2efPg","UChbyDl9DBHaJdT9nVebdUYg","UChe_4eq845O78nvJ4JJxxqQ","UChhfMuJtTUNpmLI2x-CqQkQ","UChjin9QkNdvoDAj0UxLXBkw","UChkMOeE0D-boex-v18r-gbg","UChq1aqSza4kLIQquwemYl1Q","UChtdImq0Q6roCEXRyZwMDRg","UChwX4yAaAxENs5WO-_eO7sA","UChzaxIEoCQqbARZir6T3-wA","UCi17k6Vk_GTP94-yOJgot4g","UCi2bptd4D5zrSCflp2_0Tmg","UCiB6sqdpoI3HLmpGcQ3Jybw","UCiCCZdD5EaIwyfGzHzSOVLQ","UCiEkqWfDzYdW4sGmkLR9Xgw","UCiEz6PuLH8lm4ISERVkHXJg","UCiJ690ellus2FkNKnZVwvxQ","UCiM33KO9ObvSWVWe-O3sXKw","UCiMfkG8Id6cwltrHP6_Tp4Q","UCiOiGdkFz-K3wG-p_vyN2Vg","UCiOtq8lDEQwFSc5aTC0vq3g","UCiVJbJoP5t9nBnd0pgaUtmA","UCiVilz768nvfC7zQLj2BeyQ","UCiWHqv8yq_Ble95-E9OZQGg","UCiYiVNSvcAv9Wcfp5JfOTdw","UCiZo4lXFji_q1Nw2Yk0VS5A","UCiaRa2qA5HEpoHH0IiyWUtg","UCieV57_6pg0VMRr9wzg4kdw","UCifQHU4_HLTwRkSMGKHdBtg","UCifitWoLmqM2-FdWoeMucOA","UCigSmrHcy33Oq83CIFYMKKg","UCij3Lt0y8J-EVv-sUDLpUsA","UCimAqLcp7S9fzCpepxaa_uQ","UCinV9o4xpRfmuYaIqwwHi9A","UCip2F5DxAv_UvdZfhkZUYDg","UCipghK4MIaEOxiUYCXEFzFw","UCisFu-1bm9ainEtaSLH6Eog","UCj0hr0iORxRDD3Nj4BzhnMQ","UCj69aOEeBORV3jDxFxcztLg","UCj7Py56fds7cjOCIy29BjeQ","UCjI70JALMCmTf9JVPI5PqEw","UCjILGdg98HZhVmx61XazVdw","UCjKWXNaTI8_K1EgHdyMG9eQ","UCjM7YszCMnlI0aq9cZyFUSg","UCjMEFrHjZa021lwhKwNmhfg","UCjMr3IIzujVIKv4ulCXaIAg","UCjNXzbR2U5xBcSJVERfcaJg","UCjPtvVJh3z_GCm-zfz2VsEw","UCjQqfertnBorApL3GoOANpA","UCjTt9kiGHAgLqagzCVUfTUQ","UCjTwYu1ZjIk1CXf4PlFOHag","UCjV-WzwZR2qTV80AL_nzd8g","UCjY0kPb3XnKdqvBL_0ZGDsg","UCjZlmikloiqjB-pTOvBB1pQ","UCjbTfkBhzstVrDHJ4UNq99w","UCjftg0rH4r4Dpc1nqGocxXw","UCjgZURy8VLRSr8IdoHTXvww","UCjlEAHD6C1pjt7CJLdxVIKA","UCjn05zflVbUq2DqvYHcvsWg","UCjn1IG1neQ_uBcIiOQvcKRA","UCjplfnQDDehXEUWcdZC9bDw","UCjwST3LhPUGl4r1NKKOJJ1Q","UCjz0GoGd9qv3ZVUr-uM2aSA","UCk-3u2RLus6frsc8Vuyb5jw","UCk-8tcM38hEMVNY6KGm1dPQ","UCk0JlR4d6idl1NZBcEugDAQ","UCk0mIm5SuaBzY8WGVmPkU3A","UCk1JFW88T64jZ4-70j--Bag","UCk2ohK51tLLm_dVxiTJrfsA","UCk6M-9iYZYCJHZUoyN6ggkQ","UCk9k27Mym1ksxpW97tyJzSw","UCkCkVP6eSEMH_vdLFpRZu_Q","UCkCzR0w_vzuKeP1ueErF8Hw","UCkDopF1dGQEBi_mqab-8G-w","UCkFZ4Pid53cZqSKZDKS2Jmg","UCkGxYdyjBx45zHvLQiCYCkw","UCkINQoZ_SVJRw23eTYU2EWQ","UCkIyjhKDEFclAi36pJG48xA","UCkKcioa0wtnVT4BzEmlAK3g","UCkLraYiQzVR_HvaUq3FO2Gw","UCkNt9zBltHFJrbk-rZuI-eg","UCkQCr90nSUyiTKKzAR9Zumw","UCkVd0_FFn8UUSYYhAXcli-A","UCkViSfGG62CGz1Dmg_tQuWg","UCkVmQHW09P3njYABPe4EyHg","UCk_Wo4za2y7FAxwlciAJDUw","UCkc_y3-a8G818Yjctahh1-Q","UCkf1lSw8wx1C0ERG7Kpg2Kw","UCkhmsrKjP1VOb4MsNU98-xg","UCki26pIDcsGl8TYT8OFZSJA","UCkm3Ug7NYzM-uzEsm1rvCZw","UCkmv4t-EtkaBTrlUy6CKNIQ","UCknLoZ6wX_d3ikTHvkxNwNg","UCknqkvMK2dGW2KMcWzTUzZw","UCknuiTUxR_qS6lh2o6u0FQw","UCkp6rqAAJwcom11gKbqnJig","UCkufmNW-80FuX4KKvfrUJxA","UCkuyHQuS9-hrQz71Fx9G7pg","UCkxzh42fukrtVHKIP_l1H7w","UCkzWabFrdvQWeAAPwYMcstQ","UCkzuhYBJ0nzPy7EBmrhIPog","UCl-9gFa0LempQUMsuWiIVVQ","UCl4T3VSNZh2vZP1HZnruOlw","UCl53XdPu2MO_ElvmaPKkcvw","UCl74Ll4yK0AUPp6uiTmnbhQ","UCl8PG1tIb3e_v2pp4jvVaNQ","UClB9bb6Hqtl0QdJzv7KAOPA","UClCT15ZaBAX2TF6lJGChtTA","UClDJdC1C9OsyDgQVH9bj4_w","UClEbbsM297MdVlKysBkewiw","UClFYrpN9UJ01sO2NlHQ_o5w","UClIHl3Clv1iFvtaNrc_cMqA","UClL7ZSyNvnxGMjhtYeOL0mA","UClO3tIzGSB7H2BsoKBx2Ifw","UClT2pn6xnCwm5rce35rkM6A","UClYZw2OXGevdVeyvxhhEUkg","UCl_4xmhEFuvO1AWF__pIRag","UClauDu_szAXtci-tHVUGXww","UClc9K5NK_gl6r-T6ov35G8Q","UClcPBXN2Fx-oSqmCrlRR05g","UCleLDTE_0xi_yJuHIm1kFhg","UClh0AJ3sxWhfG_VDYTwDFng","UClkjCX9jcr7BDgLTHv0n22w","UClp5zoikrs-1TeHnRr3zQOg","UClqpeS3YOeO8a6dfSAikp5A","UCls-u9z_m45bGK9X1WW-ZEA","UClsFentx5XAWtneXmZphswg","UCluPqJEkmEwlvHxr9Y2Q3-A","UClyvfiVd_apxOolCveyPlSA","UCm0FFK6lr8o3RoKJQsbp7IA","UCm48r7GM1sYaWZJbsUU4OHw","UCm4JzOibhYDWOmZtwjqYLxw","UCm6VsbK3u-2TQicGQVeWRyw","UCm8tmmDSqe9NBy3Tyq7vBfA","UCmAGuOs6zhsn2jIhG2CmHYQ","UCmGa_nv6LvGOVCEYZ5waiIQ","UCmHK810Y_F6mXE5N2d1KuIw","UCmISvbtR4d6E3xPlM3WnbVQ","UCmI_-Vj-sqqoUk-bSOQrGMA","UCmIt-kDkLjKBHGfFvcNHjqg","UCmMScndYfBEVMDJ8gQ34Zyg","UCmMoJlAjgpifu1oOnJhpxhg","UCmOByu2vGLKM6dI9q0cuxCg","UCmRhNwzQsTInMUsNTksAvjg","UCmUIYdZBslavGIcBZ9EaChw","UCm_kbGK-mot05kvKXJIpiqg","UCmakqoif2a-Av2ndDqNiG7w","UCmbtozLfuGwIsC3CvzO-zpA","UCmdoSzX2wjwsrTBhaGrVRqA","UCmeA0_-TLkWwQ8pKYvtEeBQ","UCmeCI2KP8UHxg6V-Zbs2IWQ","UCmeYAajhkIJIw-mPr9BbibQ","UCmg4yRyvLU6xxdjiFqHU3Rw","UCmkp1PpG_Ywz5SD2YJjLGPQ","UCmlRjZU83jO20n7s9KQJn7g","UCmm6Ja5uQgvYu91s7BbnYMA","UCmpi8NQNfLH_Kl-4ZWAeFwA","UCmpwDn8qb-k9FPDajs4Bqog","UCmqUdwqM1anZvGlHEc6ldBA","UCmw7klBSp1_W7tUHWF3xkxQ","UCmxIYkZK5I2y-PEbw5wQcIw","UCmxvLcKd5KgMpAS9mumVq8Q","UCmyMCDWq4EeBM22L3Fj2nUw","UCn1Bgqg9oA5CE-R8ucoWmXQ","UCn49Fbc5OUikuAHF33m7NcQ","UCn8JXZJxZJAd7kO9cT0QNOg","UCn9uqA2UZEoU4cdQqkoOLiw","UCnAFTOks1Yr92RZyQcYJPXQ","UCnCUV8gWXkpxBbInKYBIMew","UCnDVyEMTOBIlmyx5ba8Lnbg","UCnGdOt6g-Hh2nP3_BKUpMcw","UCnGk1mqJ1XrFb8748K11QNA","UCnHlYWw4gIttLj9UrSVgpjw","UCnNUF2FKKdXCGuefVzX8B6Q","UCnS89DJwZ4QiTW0qrwHRgKw","UCnThSt9EOZU6epX2NUC4hkg","UCnUOpz9dOYpqQrpannYGZMQ","UCncsX32PjwnZwI6gNVBwZ9w","UCnhN9HuXCQnhvtTRByMiUEQ","UCniXurp_3xcDh923eiqGX3w","UCnj_-Y_Hr-I5rCqJ_cR9RJw","UCnjbk_bx0IbB7NO-jc4ZF_g","UCnkD2FQ99wmScYVxjFWODbQ","UCnl9S7m9LgrozMrP7_n96HQ","UCnlNdTYPTf5MFZhXJbINrXg","UCnlXhdu5xKsrlhi5H0-VKXg","UCnme4V8JQop8lHsLcs5UV3g","UCnsee0n59Td6IB0tExNYoew","UCnszwLA2RrPB1cXACvF26hA","UCnydsOg2DexIYEtCikQmR-g","UCnyhl3aGpTMmDuZnmkziA0w","UCnzOkV6Y-gBUvr97aCfSfSA","UCo1fCi9Rg3JkBnon_sjylOw","UCo5fCtQ6SGGBZpQKsb5nBSA","UCo7619if2Up_WqN_tL8GLMg","UCo8OitRoz1ns04UgTXE1NTA","UCoAmETJYtp5IijGxsw96_cA","UCoGA7NBLeQl12bLN-6GZEDA","UCoKEDyKxz2YZmDllWOQy_1A","UCoKinFXvgZvNXst_wKRvh0g","UCoMN5VifSWN7EO6azE9VaYA","UCoMxZZueqgR2AGd1oRzJ1mA","UCoRMY54IOwrcTBSjnwJCkpg","UCoUsT2qFoviiYddx1sNnRtg","UCoV13JuEJNnc6FZ3RF0RkmA","UCoXDQy_CMHUpP6G1JHrbjZQ","UCod5titprwUVeFBFLsoxbXA","UCod6s01yHGbsgL9TcF1lwZA","UCoempMtFM8kq9qKzK9ZT9Pw","UCohoi1xQ7OdNGh46Fbud7qw","UCom2dKkzY6lqt__XqksQlnw","UCon1IG4I7l3vjqA-xrBLA_A","UCon6VE0cRvcIfDcKoRJ0Taw","UCooVaarbL012MNF5-ZKCauQ","UCos2Fo_VuJxuykACwBdt6QA","UCos4C8j2xlZarflGN7uJeXQ","UCowUBYYpgOpUsPRYWspr2Iw","UCozQ_IjTlwu216qH4xeRDvQ","UCp-Xdp1FYimywvOQPIvbngw","UCp-ygaJhPGrvWIZQzBNdZuA","UCp08VBh4q50Pm1oXUcCR6Sw","UCp1B8UoWue4nz5iMUXjaUSg","UCp3WkyHCBK13q_PpYzCoIiw","UCp3_jkkyidIcQYpU8_Fo8DA","UCp4sKNjNfyA-KypLjMCndzw","UCp7CuPOJvj_2Nvl0Bnq-c1g","UCp9oWJZlb74lHqBeee-lWSQ","UCpAtGqHm1i94dSFiy2tSl3Q","UCpC4i0JmKHNhdiU0Rpi8XmA","UCpC4irW1lwIB2dFH2sxT8eA","UCpE49xooogpQzjWGKOuEJkQ","UCpKPtbiHIdtbkkTf4JXz5SA","UCpMttSRJ6o33c_eL1LfsGYQ","UCpP8mpl05nipGkaM9BHrLSA","UCpQVSTwu1Z-f7Iqnd5dd2rQ","UCpTUX98D6sGzCEXeoTskddA","UCpTVLVAM8TexFctrLI7Zcfw","UCpUwzWCoNpDXPGFaTm5p4Wg","UCpW3PbISF42tMe8ER28VtUA","UCpXAoLgrnxvDX1z9wEfiMzw","UCpY9mHiaHDkA3xO9SDi2Pfg","UCpZfUXprXKsHF5C7tndJB-g","UCp_B7rTlHMntrCbzljEW_0A","UCpdTc9Ldp2ggL3_UNzN2UfQ","UCphj6XCPXLtfRY40LmyKC1A","UCpiF3G-6qYFOFldffgOOmMQ","UCpl9dyz5mCYu8Q9lzJPJuRQ","UCpmlMEXaMZTvNna0OKAUv8g","UCpnhRUjd2EgxPggNMKzNmcA","UCpqTfNTF4q1sgAqLyYfo4og","UCpr4Rd0OfMWHsLzMqPWqumg","UCpsE1RU7TkJeF8BK7rTfjiQ","UCptfKT1TIkoFdg-EBjid4fg","UCpvJ5em8FRMFlzQa2Z1u-Lg","UCpvtFPW9TQjbOSuvjt8NwEw","UCpwjxWuPxNnaIaIDasICGog","UCpxy9Po2KOd4CvymavZrwZw","UCq98DEWFS1ORVZocee1SiGw","UCqAmO_XRnjoPGN85axH465g","UCqB_m6ShwhRWsmVIByfHmvw","UCqBteKi_CN3ayT7o69MtK-g","UCqCfzq85Z90Fxhj_GB_uycQ","UCqDls2stT7ecVSqZ20FuGiw","UCqHHVtE2O7PrZ9v63FqwP0w","UCqHJ1biz3n51bfGLn-zsYBA","UCqI85XLIpRB3t0Y5uWK6euw","UCqKyhkjdzRUj3qlwvDzEmPA","UCqN5S8qt1gbnldAMCaVZhQw","UCqOTD3jgr64yzJED-9hCnbg","UCqP8N-UvtVKtZYI6EqdoAPQ","UCqPGhQiouA7jplKGJaSSN-g","UCqQGWqkZ-0jY28rV-czuT-Q","UCqQxwOspPPaBWgQpu-upSKw","UCqRK1crCW7AUs51XBJtEgIA","UCqRRwxUMNSbwb9H8a6r2VwA","UCqXL697Z0fyMQ5HKS4COUfQ","UCqbaQIL5kp_Z_sy3NAp3vHA","UCqciv3hGTHJfgu-A5DZaLfA","UCqcp-LS5IYruv0KoqiGptzQ","UCqdJUY1SWrd0nj-67PhCuag","UCqez4kVknYIII9pSjrpq5oQ","UCqgRpHrUbHfOmlYJGrL3Wfg","UCqicIN6k9e67RRxAajQJfMw","UCqlgc-TjXQ4Q5-rn4g3andA","UCqoVkV-BK--Ky1SksLfNBMQ","UCqoXAq4s50vrPp1W8ePlGYw","UCqqHjJu2olDFSCzsjDJ5SwQ","UCqqK2SARG-QOsg5cGkbkZAQ","UCqtkh2up79yPOLD8EIjjjwA","UCqy7OPNktChqDPlr4GZ0OkA","UCrByX64IlVKt0p-nmofEh_w","UCrCpsD-9EG4OX4-cR5R0LpQ","UCrDMqfnhZeyFBa5rHjyRqig","UCrFD-3RS2Db1aKVDJ7qUavg","UCrIm1RZxBm8JTctRGvcWXKQ","UCrOBf6culN1OgaevibldBzg","UCrOsi1fnOqqlyon2FtsEAQg","UCrSiEnMDLKUltbCuy_2yDZg","UCrTMCyp0OHIce4ZlNTPSQeA","UCrXvbjlqUO3RYhJZgyGF-dg","UCr_KG1yaforpU6ZJkcW97yA","UCrbTIcOTp1WkdAIxQSY6W_A","UCrcjM6CXocyy41p8lg4bIqw","UCrd9DT8w9oCS23GCfWkg2Ig","UCreUmRP6Zy05OB4yg8xJWBA","UCrjE6klqriuLOE1LKTZBbVA","UCrlm9xZasVwBotURW6PLxPQ","UCrms3QwYQR2eX4_5I1hvkIA","UCroR44Np6UnKqa6xYnqAf8w","UCrsycZKcIBiodaqTTaUkI-A","UCrx-N5xXXJJuNtP7h_cHjIQ","UCrx12ZDHMEzk_3NiRXma2bg","UCs12r2OMjG7ve1bcR_KHt_w","UCsAiaSZGKpVHwVtUi1QmB0A","UCsAngOfVcQD-cLGnChTgMgA","UCsDvbyxhoaczH5rGutBkbDA","UCsFK3MR9kuvuYiVCQ08c8zQ","UCsG35cCyUsKcnofCVkm0NlQ","UCsG3Hv3kOkZ7Yldm_lyblbw","UCsKEvVfbzxNSm1Gp6sVNKdw","UCsMs6MKnfo_p5hgAYMF71YQ","UCsUFtSovXUNk4nT7iVfVDfw","UCseBJjnfEEK2Ibull4L7kBg","UCsf20UztvMR5AcriKVOdoTA","UCsfyf6JgIpn1PofxUjbrzAg","UCsgmd8AAHilycvJqhFqwVYw","UCshLgmOav-X1U0njQUeXdKQ","UCsj2MiFfDTeIg9t2QL98cFQ","UCsmROkGVSer9Ku2E7LtW2qg","UCsneMtybFahKHV0aBQNBkyQ","UCso0R1IVklTl-y_LR5Vhq6Q","UCsyX5DmLxEYAk3Z4ZQUMScw","UCsysrbIc5t-KRvkoodlEpkA","UCszE02ehm1M97M6MRo0Ve3Q","UCszFzXXU0C1WScaDmj8W5_Q","UCt3MN1FUWrwQ8wILGD5GVHg","UCt7vNWXVKEJfT9M6vJOwX1g","UCt8Y5wHq11xF6dX-zv6jYHg","UCt8p5RX15zlH8URCqJwDJ1Q","UCtB-TsKHRkvxPmkvM0INXzg","UCtE8i8_JjW3TC3Psz-VyJxw","UCtEV0n4CYcUaIUa26XNgLwQ","UCtGSDJrZ6ZjSLqa-F0yAHtA","UCtJXYNrA6OjmhVAp5mUOtNA","UCtK-KczUMdc4Yu3ShfjowUw","UCtRKZiO0r-4M69RyEE32b6g","UCtT3lxHan0XXMe8xUN39ZbQ","UCtUpy6_q2KaTzXjBwzmxq_A","UCta0nPZrrVFKpS7uuM3UZFQ","UCtcByOc6O2KlgOtnptMDSTA","UCtdWc27oY6Ilxsf7ASRDrPA","UCtenKBArzDYikSe01d5rmtw","UCtjuprxFG0EAOkDMiyd2ATA","UCtkB58pMIAk-bHsPfff9fpg","UCtnh-OqB7RS7XiTx73CtYnQ","UCto8HhUuq_7m6vnogiOVmlg","UCtoIfAV5LLg9G77EkNKINuA","UCty8QosxI3MmxswGVaZI3Lw","UCtzzGCB2fPblpKA_1PdXm0Q","UCu11lQxxrs6lVQLRo9NDrWw","UCu1JILHoeuGH4VmbgDXlxHQ","UCu7t8xPPP6b7RBls6PWtyNA","UCu9SCMU1BQo0UE0hV8BU1RQ","UCu9vpeS06KcASCsqDZIXDYA","UCuD-FH9WTn20-IMCmGDiwAQ","UCuLIe-a-Ec5gXeYH2_tk2-g","UCuLoOMRm0bp8ThsehUvhwPA","UCuOEZiJrJ8xDJhTBcLgfMEg","UCuQ3PtCcg9hHOpdPSc1m-wA","UCuREh7fOgFKfaJcvuLmUVSw","UCuROzNGmTNIMfaXGszHUyQQ","UCuSZNHe8f1I25uogXTVqsHg","UCuTDpzVrV0EHCSJ_NABDaLw","UCuU8RHa4InGLMzoKtPBgVKw","UCuUyvpHsusHYATLgdxZhauQ","UCuX8eiePgeNm9xzol0-ce_w","UCuXl3lR9vJQXgMcmPVNfOOw","UCu_3DGwbTYN4s7a7SlBNxQQ","UCu_ShnXukzhg45y8ZmUn_Gw","UCufCuEUpXYUzeWs0wM0WfYQ","UCum8MDrQrBMfkDmgbhQ6mmg","UCunxkgPVGirDR4TUBWwK7jA","UCurN85VeS705fTui_YfV5jA","UCurUtxpX8H8_wrQCShqc4hQ","UCurqxMtidnWOYJ4uwbeabcg","UCuu8fhqbEGl593BT0Fq1v0w","UCuvt6ijRbn5EgeKSMfP4PuA","UCuwjzrkvEX4OFNRg3lQGP0Q","UCuwvVzxzwsBxCsRJM4JoauQ","UCuzPAS2i002CY1LByMFeeow","UCv-9BMY2KIEMUHlkQ2dhuMg","UCv17rw50bU7zLSum2lZ_P8g","UCv5pew4Lr-WaCHuFuKTElog","UCv6nd5PJ2VHq7gP_G81hHvQ","UCv8jDUBznVhTRGaRv84DyAg","UCvAluwHl-VVUZDot0SFvrNA","UCvFX82Zek6d0JcoOS_07JYw","UCvLGZTwE57Yyp1x1o08iTeQ","UCvPpiCHR_b6IcVsZbNvWezA","UCvVmIcWNXKuu3IeNLpRIZiQ","UCvX6Ns9NROxuawH-5WyqNIg","UCvX7nfme92VYehJvqHIoCzA","UCvaHbJcABM8iP0Sl0PddPvA","UCvaaDEvAF65KbeZXgrQZQSw","UCvcmJpsUpkVBaK6wheYmz7A","UCvjTPJpYm83_ZKT8Tis8IgA","UCvm8KjBhrCWaaGeJVa8rL0A","UCvpYQOy_nHrs8EQEt0ikTjg","UCvpa0gyJZZEKivgNlqXVuPw","UCvqP4GCHrR6qfSnqos160uQ","UCvrleKFvR16PyNb4M1LxygA","UCvvCWsB-BHnOSCcE0ZMKtPA","UCvvr8YQDIMD_4MtiGKMrOoA","UCw3Ju5JyfxadyCrjw5tIBfg","UCw51O4ddk1zv2qPP7FASdnw","UCw8I7QRsKPX5qmt0-d4b84w","UCwIgt6fuma2MK3aawqCZ64g","UCwJn4jjtjbFpI3SbBf67Rsw","UCwLr0-i8AxCMdw3ycWQ-DuA","UCwRUo2hLI9eBW_QY05TrGIQ","UCwTutD9-LJ0OAcbMneehG-A","UCwU-Fj5e2c-IXyz54KL5naw","UCwUmlyQglTSi8sfQa4vvW-g","UCwauHHjvJYiG1r_VX8025QA","UCwbfhbEGOO1kV87wEYGdrww","UCweZ1VQaVEfZ7LyRLeVJQqA","UCwf1zyGHmDDMYcrE54ipILg","UCwfpkUKq8iKxt7WyeNL5p5A","UCwkx7HY9u9wlp2GNd5KF6Pw","UCwm9o-lUYieMTmgQbghZPfw","UCwnUzgw6-fQkoMXeehOpO-Q","UCwnk_0Ju5YVg_RlODhdoYcg","UCwo8uGs9TfaurTpHXRN5Yzg","UCwq6JB4tHRo9g7lky3i0egQ","UCwtir0D7FKA3RStNlwKy7zA","UCwvId1ISfKZOeiHKFMOp4hg","UCwzyMfgNq-mwskTtBWt3ovA","UCx2lABT88rn5vznp1m-oI9g","UCx3i-2N4sXz_mpYpblP_lSg","UCx4aVhiZkvTfmlmylXkuGJw","UCx4lWRvwOMuO5bPHuWd1f8Q","UCx5fgl2FjPr9ukF1WX_k46A","UCx9bAseHghwMKY-2ys96yXA","UCxA5rEiZc4O_LGDMN08h8pw","UCxCG_LjW0DuSjhbuTYO0vVw","UCxJ9dq8fM63MmktJaR-jK5w","UCxNHY0BZBLJ7DNPI5Cp4oHA","UCxNY-8ARgu87Qj3o4ziGOOQ","UCxPMp7o-CnzRS6r4_9eutWA","UCxdKXfyiPbVYFCsRf95r_qw","UCxe_RK89ebYURmqVZIM-MaQ","UCxha2BLNmfzZS8Ddm39cPbw","UCxi9hZwxUGjfq7cBSb2A_nA","UCxjGF3zRTiWwO2-3Jy6mO4Q","UCxjmfHawxoCLPFC_TNdLCXA","UCxk_Bot5XGIhpKR2u1k9X_A","UCxmRRk1cMKEg6wvjHyefCsg","UCxpIJetdh4auTgEtCOzplMQ","UCxq-lEeDujQxtYWczSueBaA","UCxtnqgntRDJZeZOy2kNJydw","UCxwDWNlmhAxFJONQ56TE7cA","UCxwae6F1grDlNJv8mo9j3bg","UCxy2iz8mD1XLS-h2PzAPPLA","UCy1dLfveAzcd9NIWjjfrD6g","UCy1sJkoCVrbVAuDLXXLgdlw","UCy1vNodQO46pQ4CFnzygRfw","UCy6OfG6e0CcKWMN7iUZfaew","UCy9FvvVrvTjkJi2c1xI6Evw","UCy9XQnvtPCMWXhalKHjgFfA","UCyAS41aiU6fnGQ2oWnhHRkA","UCyHLxDepMJJ7QRRrQRT13eg","UCyHYoT1mHrOoz1S4zi6T8vQ","UCyLDI6BYvCUnFdQGm8WfbjQ","UCyPJAMJVUOKorZ0xrI6pMzg","UCyQ0o9C0qfLqZ7IP8bv2VZQ","UCyS4fa1PmE5hjJJHQxZqJiA","UCyUOLER_t9WUsj9rlqWWl0Q","UCyW8PZGGn4geNXzNW-Hb1Eg","UCyXE2D2V8nfPx-jndhgfzNA","UCybHUtiyiYMK1Jg3n6xXYqQ","UCybdUUNUKFTsYvyeL7zfE2w","UCycLR0kV2DzgEsafBMHz8-A","UCyeCuulZUlQ0U0jYQhxmeCQ","UCyeqR55Qv3adK8LQfekzY5Q","UCygkJM_-iU9MscSRKFXVcDg","UCygpivsf2sCVUV5pVOK3ePg","UCyiLVXxmtGWzOdp5PuC2F0g","UCyqi0FwTteQSv_29O94sgDg","UCyuyjRgxTKBlEJOLMpubxXg","UCyxrrXqTgaJ_VWstRPb3iyg","UCz2sAHSwD_30C7Xyyn3R4Lg","UCz8S857Bf_6rBG-W9KL4MUg","UCz94iOzwTEn-AGXPT_dXq4A","UCz9cCz98RRxdbiM1A04D9pA","UCz9sCqUpKF2N953_DZelzeg","UCzBnkfC-Gh2UuL8vpg9lZIw","UCzDQ2rSq2FJQrQkfmrSqu2g","UCzG_nRbV-iJTG0o6kZEkxwA","UCzGkcHf_U1lER_XtZahcTlg","UCzHT7Aygc5l7swKQ6GFpRNQ","UCzHtcAUVtpo0RKugO2NaGyQ","UCzKopU95FWwfgFMwS6M2c8g","UCzLmoPdrNwxnlUEQZromiHQ","UCzM4sxNQXk3r1GDmWBaSpYA","UCzO_Thls2ty6LnFi_hXAAyA","UCzQthgyVFN5E0TabYGBXbsw","UCzYAIeLx6o-msAAUIUkcO3Q","UCzYV4GBBGeUTljGhQpVhAiA","UCzYmDtaI4FqJHRB4SNl57Tg","UCzZSOiRJtlcaXDNGeUUfMUg","UCzcjbIy0xyoEiHTG8JnQ8vQ","UCzh-Y6jhWjfgs-1Hjm_ysxA","UCzhHgmHRoYEhrhWSncBUHOQ","UCzjJf00RETyvYra3yiQv7Aw","UCzkkNTM47G7Zz_baVTiH0nQ","UCzn_o0o6ZAbMobK4f2bRE4g","UCzrxdiOLhhi4AbtJWZ4nwPA","UCzv1F9_DMOOlTvHoL2MvHRw","UCzyNGQyE04gJ2ZDeGFydWuw"]



channel_list = []
video_list = []
counter = []


# Set up a logger, formerly 'example.log'
logging.basicConfig(filename='sheepdog.log',level=logging.DEBUG) 
logger = logging.getLogger(__name__)


# The CLIENT_SECRETS_FILE variable specifies the name of a file that contains
# the OAuth 2.0 information for this application, including its client_id and
# client_secret. You can acquire an OAuth 2.0 client ID and client secret from
# the Google Developers Console at
# https://console.developers.google.com/.
# Please ensure that you have enabled the YouTube Data API for your project.
# For more information about using OAuth2 to access the YouTube Data API, see:
#   https://developers.google.com/youtube/v3/guides/authentication
# For more information about the client_secrets.json file format, see:
#   https://developers.google.com/api-client-library/python/guide/aaa_client_secrets
CLIENT_SECRETS_FILE = "client_secrets.json"

# This variable defines a message to display if the CLIENT_SECRETS_FILE is
# missing.
MISSING_CLIENT_SECRETS_MESSAGE = """
WARNING: Please configure OAuth 2.0

To make this sample run you will need to populate the client_secrets.json file
found at:

   %s

with information from the Developers Console
https://console.developers.google.com/

For more information about the client_secrets.json file format, please visit:
https://developers.google.com/api-client-library/python/guide/aaa_client_secrets
""" % os.path.abspath(os.path.join(os.path.dirname(__file__),
                                   CLIENT_SECRETS_FILE))

# This OAuth 2.0 access scope allows for read-only access to the authenticated
# user's account, but not other types of account access.
#YOUTUBE_READONLY_SCOPE = "https://www.googleapis.com/auth/youtube" #.readonly
YOUTUBE_READ_WRITE_SSL_SCOPE = "https://www.googleapis.com/auth/youtube.force-ssl"
YOUTUBE_API_SERVICE_NAME = "youtube"
YOUTUBE_API_VERSION = "v3"

flow = flow_from_clientsecrets(CLIENT_SECRETS_FILE,
  message=MISSING_CLIENT_SECRETS_MESSAGE,
  scope=YOUTUBE_READ_WRITE_SSL_SCOPE)

storage = Storage("%s-oauth2.json" % sys.argv[0])
credentials = storage.get()

if credentials is None or credentials.invalid:
  flags = argparser.parse_args()
  credentials = run_flow(flow, storage, flags)

with open("youtube-v3-discoverydocument.json", "r") as f:
  doc = f.read()
  youtube = build_from_document(doc, developerKey="AIzaSyBRgM5ARXMih_F9HviEUFYDpnkEmA4FPCs", http=credentials.authorize(httplib2.Http(cache=".cache")))

logger.info("Youtube build established.")

# Alternative "build" method to create youtube object
# youtube = build(YOUTUBE_API_SERVICE_NAME, YOUTUBE_API_VERSION, developerKey="AIzaSyBRgM5ARXMih_F9HviEUFYDpnkEmA4FPCs", http=credentials.authorize(httplib2.Http()))





# Part I - Retrieve the video uploads for a channel

def get_channels(youtube, channelId):
  """Retrieve the contentDetails part of the channel resource for the
     authenticated user's channel."""
  channels_response = youtube.channels().list(
    id=AUTH_USER_CHANNEL_ID,
    part="contentDetails"
  ).execute()
  
  return channels_response["items"]

def get_uploads(channel)
  video_list_uploads = []
  """From the API response, extract the playlist ID that identifies the list
     of videos uploaded to the authenticated user's channel."""
  try:
    uploads_list_Id = channel["contentDetails"]["relatedPlaylists"]["uploads"]
  except KeyError:
    pass

  try:
	"""Retrieve the list of videos uploaded to the authenticated user's channel."""
	playlistitems_list_request = youtube.playlistItems().list(
	  playlistId=uploads_list_Id,
	  part="snippet",
	  maxResults=50
	)
  except NameError:
	pass

  try:
	while playlistitems_list_request:
	  try:
	  	playlistitems_list_response = playlistitems_list_request.execute()
	  except HttpError:
	  	pass
	  for playlist_item in playlistitems_list_response["items"]:
		video_id = playlist_item["snippet"]["resourceId"]["videoId"]
		video_list_uploads.append(video_id)
		
		# Returns the title of the video, if needed
		# title = playlist_item["snippet"]["title"]
		# Prints the title and videoId for testing, if needed
		# print "%s (%s)" % (title, video_id)
	  try:
	  	playlistitems_list_request = youtube.playlistItems().list_next(
	  	  playlistitems_list_request, 
	  	  playlistitems_list_response
	  	)
	  except HttpError:
	  	pass
  except NameError:
	pass

  return video_list_uploads

    




  
# early code; this works for sure, leave it in to test if needed

# channels_response = youtube.channels().list(
#   #mine=True,
#   id=ANY_CHANNEL_ID, #id field here can be used for any channel id, to look up video ids in a playlist
#   part="contentDetails"
# ).execute()
# 
# for channel in channels_response["items"]:  
#   try:
# 	uploads_list_id = channel["contentDetails"]["relatedPlaylists"]["uploads"]
#   except KeyError:
# 	pass
# 	
#   try:	
# 	print "Videos in list %s" % uploads_list_id
#   except NameError:
# 	pass
#   
#   try:
# 	# Retrieve the list of videos uploaded to the authenticated user's channel.
# 	playlistitems_list_request = youtube.playlistItems().list(
# 	playlistId=uploads_list_id,
# 	part="snippet",
# 	maxResults=50
# 	)
#   except NameError:
# 	pass
# 		
#   try:
# 	while playlistitems_list_request:
# 	  try:
# 	  	playlistitems_list_response = playlistitems_list_request.execute()
# 	  except HttpError:
# 	  	pass
# 	  # Print information about each video.
# 	  for playlist_item in playlistitems_list_response["items"]:
# 		#title = playlist_item["snippet"]["title"]
# 		video_id = playlist_item["snippet"]["resourceId"]["videoId"]
# 		#print "%s (%s)" % (title, video_id)
# 		video_list_uploads.append(video_id)
# 	  try:
# 	  	playlistitems_list_request = youtube.playlistItems().list_next(playlistitems_list_request, playlistitems_list_response)
# 	  except HttpError:
# 	  	pass
# 	  print
#   except NameError:
# 	pass
# 
# 
# for line in video_list_uploads:
# 	print line
# 
# time.sleep(5)



# Part II - get unique commenters for a channel

#### added this part in

# Get the unique commenter channelIds from a channel
 
# def get_comments(youtube, video_id, channel_id):
#   results = youtube.commentThreads().list(part="snippet", videoId=video_id, allThreadsRelatedToChannelId=channel_id).execute()
#   
#   global nextPageToken
#   
#   nextPageToken = results.get("nextPageToken")
# 
#   for item in results["items"]:
#   	comment = item["snippet"]["topLevelComment"]
#   	author = comment["snippet"]["authorDisplayName"]
#   	authorChannelId = comment["snippet"]["authorChannelId"]
#   	channel = authorChannelId.get("value")
#   	
#   	channel_list.append(channel)
#   	
#   return results["items"]
#   
# def get_more_comments(youtube, video_id, channel_id):
#   results = youtube.commentThreads().list(part="snippet", videoId=video_id, allThreadsRelatedToChannelId=channel_id, pageToken=nextPageToken).execute()
#   
#   global nextPageToken
#   
#   nextPageToken = results.get("nextPageToken")
#   
#   for item in results["items"]:
#   	comment = item["snippet"]["topLevelComment"]
#   	author = comment["snippet"]["authorDisplayName"]
#   	
#   	try:	
#   		authorChannelId = comment["snippet"]["authorChannelId"]
#   	except KeyError:
#   		pass
#   	
#   	channel = authorChannelId.get("value")
#   	
#   	channel_list.append(channel)
#   	
#   return results["items"]
#   
# get_comments(youtube, None, "UCXqK1FO9yS8x7CMGkzLgJmA")
# 
# time.sleep(10)
# 
# logger.info("get_comments method successful.")
# 
# while nextPageToken:
# 	get_more_comments(youtube, None, "UCXqK1FO9yS8x7CMGkzLgJmA")
# 	time.sleep(10)
# 	
# logger.info("get_more_comments method successful.")
# logger.info("channel_list populated.")
# 
# uniques = list(set(channel_list))
# uniques.sort()
# 
# logger.info("uniques list populated and sorted.")
# 
# for line in uniques:
# 	print line

##### #####

# channels_list = ["UCdLWVR1C-hwcW4i558GeZ1A", "UChuJTHTRhqBTsP3KCKyIieQ", "UCTWdDAN_QrxWSumDs0z2bpA",
# "UCQYfPb1c6_vDLAbGxSRUT5A"]

# t0 = time.time()
# for channelId in uniques:
# 	video_list = []
# 	#Retrieve the contentDetails part of the channel resource for the
# 	#authenticated user's channel.
# 	channels_response = youtube.channels().list(id=channelId, part="contentDetails").execute()
# 	#mine=True
# 	
# 	for channel in channels_response["items"]:
# 		try:
# 			uploads_list_id = channel["contentDetails"]["relatedPlaylists"]["likes"]
# 		except KeyError:
# 			break
# 			
# 		try:
# 			print "Videos in list %s" % uploads_list_id
# 		except NameError:
# 			pass
# 		
# 		try:
# 			playlistitems_list_request = youtube.playlists().list(
# 			id=uploads_list_id, 
# 			part="contentDetails" 
# 			#fields="etag,nextPageToken,items(snippet(thumbnails/default,title,resourceId(videoId)))",
# 			#maxResults=50
# 			).execute()
# 			
# 			for playlist_item in playlistitems_list_request["items"]:
# 				count = playlist_item["contentDetails"]["itemCount"]
# 				print "%s,%s" % (channelId, count)
# 		except NameError:
# 			break
			
# 		try:
# 			while playlistitems_list_request:
# 				try:
# 					playlistitems_list_response = playlistitems_list_request.execute()
# 				except HttpError:
# 					pass
# 				for playlist_item in playlistitems_list_response["items"]:
# 					title = playlist_item["snippet"]["title"]
# 					video_id = playlist_item["snippet"]["resourceId"]["videoId"]
# 					#print "%s (%s)" % (title, video_id)
# 					video_list.append([video_id, title])
# 				playlistitems_list_request = youtube.playlistItems().list_next(playlistitems_list_request, playlistitems_list_response)
# 				time.sleep(1)
# 			print "%s,%s" % (channelId, len(video_list))
# 		except NameError:
# 			pass
# 			
# t1 = time.time()
# total1 = t1-t0
# print total1


#### should take longer (this is the original)

batch = BatchHttpRequest()

t0 = time.time()
for channelId in uniques:
	video_list = []
	#Retrieve the contentDetails part of the channel resource for the
	#authenticated user's channel.
	channels_response = youtube.channels().list(id=channelId, part="contentDetails").execute()
	#mine=True
	
	for channel in channels_response["items"]:
		try:
			uploads_list_id = channel["contentDetails"]["relatedPlaylists"]["likes"]
		except KeyError:
			break
			
		try:
			print "Videos in list %s" % uploads_list_id
		except NameError:
			pass
		
		try:
			playlistitems_list_request1 = youtube.playlistItems().list(
			playlistId=uploads_list_id, 
			part="snippet",
			pageToken="", 
			maxResults=50
			)
			
			playlistitems_list_request2 = youtube.playlistItems().list(
			playlistId=uploads_list_id, 
			part="snippet",
			pageToken="CDIQAA", 
			maxResults=50
			)
			
			playlistitems_list_request3 = youtube.playlistItems().list(
			playlistId=uploads_list_id, 
			part="snippet",
			pageToken="CGQQAA", 
			maxResults=50
			)
			
			playlistitems_list_request4 = youtube.playlistItems().list(
			playlistId=uploads_list_id, 
			part="snippet",
			pageToken="CJYBEAA", 
			maxResults=50
			)
			
		except NameError:
			break
			
# 		try:
# 			while playlistitems_list_request:
# 				try:
# 					playlistitems_list_response = playlistitems_list_request.execute()
# 				except HttpError:
# 					pass
# 				print playlistitems_list_response
# 				for playlist_item in playlistitems_list_response["items"]:
# 					title = playlist_item["snippet"]["title"]
# 					video_id = playlist_item["snippet"]["resourceId"]["videoId"]
# 					#print "%s (%s)" % (title, video_id)
# 					video_list.append([video_id, title])
# 				playlistitems_list_request = youtube.playlistItems().list_next(playlistitems_list_request, playlistitems_list_response)
# 				time.sleep(1)
# 			print "%s,%s" % (channelId, len(video_list))
# 		except NameError:
# 			pass

		def list1(request_id,response,exception):
			print response
		
		def list2(request_id,response,exception):
			print response
		
		def list3(request_id,response,exception):
			print response
			
		def list4(request_id,response,exception):
			print response
			
		batch.add(playlistitems_list_request1, callback=list1)
		batch.add(playlistitems_list_request2, callback=list2)
		batch.add(playlistitems_list_request3, callback=list3)
		batch.add(playlistitems_list_request4, callback=list4)
		
		batch.execute(http=credentials.authorize(httplib2.Http(cache=".cache")))
		
			
t1 = time.time()
total2 = t1-t0
print total2

# 
# for line in video_list:
# 	counter.append(video_list.count(line))
# 	
# logger.info("counter list populated.")
# 
# for line in video_list:
# 	line.insert(0, counter[video_list.index(line)])
# 	try:
# 		line[1] = str(line[1])
# 		line[2] = str(line[2])
# 	except UnicodeEncodeError:
# 		pass
# 
# logger.info("video_list populated with counter.")
# 
# video_list.sort()
# 
# final = list(video_list for video_list,_ in itertools.groupby(video_list))
# 
# logger.info("final sorted and duplicates removed.")
# 
# final.sort()
# 
# #remove video ids belonging to initial user channel
# 
# for line in video_list_uploads:
# 	for i in final:
# 		if i[1] == line:
# 			final.remove(i)
# 			
# for line in final:
# 	print line
# 	
# logger.info("Script completed successfully.")
# 	  
# # 	  while playlistitems_list_request:
# # 		playlistitems_list_response = playlistitems_list_request.execute()
# # 
# # 		# Print information about each video.
# # 		for playlist_item in playlistitems_list_response["items"]:
# # 		  title = playlist_item["snippet"]["title"]
# # 		  video_id = playlist_item["snippet"]["resourceId"]["videoId"]
# # 		  print "%s (%s)" % (title, video_id)
# # 
# # 		playlistitems_list_request = youtube.playlistItems().list_next(
# # 		  playlistitems_list_request, playlistitems_list_response)
# # 
# # 	  print